#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_105721_BP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_105721_BP.Ability_105721_BP_C
// 0x0000 (0x2C28 - 0x2C28)
class UAbility_105721_BP_C final : public UAbility_105
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Ability_105721_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Ability_105721_BP_C")
	}
	static class UAbility_105721_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_105721_BP_C>();
	}
};

}

