#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_200401_BP

#include "Basic.hpp"

#include "PyAbility_200401_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_200401_BP.Ability_200401_BP_C
// 0x0000 (0x2D00 - 0x2D00)
class UAbility_200401_BP_C final : public UPyAbility_200401
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Ability_200401_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Ability_200401_BP_C")
	}
	static class UAbility_200401_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_200401_BP_C>();
	}
};

}

