#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_101621_BP

#include "Basic.hpp"

#include "PyAbility_101621_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_101621_BP.Ability_101621_BP_C
// 0x0000 (0x2B38 - 0x2B38)
class UAbility_101621_BP_C final : public UPyAbility_101621
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Ability_101621_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Ability_101621_BP_C")
	}
	static class UAbility_101621_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101621_BP_C>();
	}
};

}

