#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_105041_BP

#include "Basic.hpp"

#include "PyAbility_105041_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_105041_BP.Ability_105041_BP_C
// 0x0000 (0x2BA8 - 0x2BA8)
class UAbility_105041_BP_C final : public UPyAbility_105041
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Ability_105041_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Ability_105041_BP_C")
	}
	static class UAbility_105041_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_105041_BP_C>();
	}
};

}

