#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_105931_BP

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "PyAbility_105931_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_105931_BP.Ability_105931_BP_C
// 0x0EF8 (0x3A28 - 0x2B30)
class UAbility_105931_BP_C final : public UPyAbility_105931
{
public:
	struct FDashAbilityInfo                       Dash_Info;                                         // 0x2B30(0x0EE8)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UGATask_WaitInput*                      InputTask;                                         // 0x3A18(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsTriggerInput;                                   // 0x3A20(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Ability_105931_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Ability_105931_BP_C")
	}
	static class UAbility_105931_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_105931_BP_C>();
	}
};

}

