#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KnockUp_104432

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass KnockUp_104432.KnockUp_104432_C
// 0x0000 (0x2470 - 0x2470)
class UKnockUp_104432_C final : public UMarvelKnockUpAbility
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("KnockUp_104432_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KnockUp_104432_C")
	}
	static class UKnockUp_104432_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKnockUp_104432_C>();
	}
};

}

