#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_105506

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"
#include "Hero_1055_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_105506.PyConfig_105506
// 0x0EF0 (0x2B40 - 0x1C50)
class UPyConfig_105506 final : public USelectAbilityConfigBase
{
public:
	uint8                                         Pad_1C48[0x8];                                     // 0x1C48(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDashAbilityInfo                       DashInfo;                                          // 0x1C50(0x0EE8)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyConfig_105506")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyConfig_105506")
	}
	static class UPyConfig_105506* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_105506>();
	}
};

// PythonClass PyAbility_105506.PyAbility_105506
// 0x0000 (0x2BA8 - 0x2BA8)
class UPyAbility_105506 : public UAbility_105506
{
public:
	void BeginPlay();
	bool CanActivate();
	void NativeOnMontageCompleted(const class FString& Tag);
	void NativeOnMontageCancelled(const class FString& Tag);
	void NativeOnMontageInterrupted(const class FString& Tag);
	void MissileEventNotify();
	void OnDashFinish(EDashStopReason Reason);
	void BreakEventNotify();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyAbility_105506")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyAbility_105506")
	}
	static class UPyAbility_105506* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_105506>();
	}
};

}

