#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_104243

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_104243.PyAbility_104243
// 0x0000 (0x2B28 - 0x2B28)
class UPyAbility_104243 : public UMarvelGameplayAbility
{
public:
	void BeginPlay();
	void K2_ActivateAbility();
	void OnTargetActorEnd(class AActor* TargetActor);
	void K2_OnEndAbility(bool bWasCancelled);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyAbility_104243")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyAbility_104243")
	}
	static class UPyAbility_104243* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_104243>();
	}
};

}

