#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_105321

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"
#include "GameplayTags_structs.hpp"
#include "Hero_1053_structs.hpp"
#include "Hero_1053_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_105321.PyConfig_105321
// 0x0120 (0x01C8 - 0x00A8)
class UPyConfig_105321 final : public UConfig_105321
{
public:
	struct FStateChangedTaskParam                 ActiveUserSetting;                                 // 0x00A8(0x0028)(Edit, NoDestructor, NativeAccessSpecifierPublic)
	int32                                         ScopeID;                                           // 0x00D0(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D4[0x4];                                       // 0x00D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  BlockReduceTag;                                    // 0x00D8(0x0068)(Edit, NativeAccessSpecifierPublic)
	struct FGameplayTagContainer                  BlockEnergyUITag;                                  // 0x0140(0x0068)(Edit, NativeAccessSpecifierPublic)
	int32                                         EnergyReduceBuffID;                                // 0x01A8(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         SkillEnergyMax;                                    // 0x01AC(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AttenuationDelay;                                  // 0x01B0(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AttenuationEnergy;                                 // 0x01B4(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FEnergyRateInfo_105321>         EnergyIncreaseInfo;                                // 0x01B8(0x0010)(Edit, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyConfig_105321")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyConfig_105321")
	}
	static class UPyConfig_105321* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_105321>();
	}
};

// PythonClass PyAbility_105321.PyAbility_105321
// 0x0010 (0x2B38 - 0x2B28)
class UPyAbility_105321 : public UMarvelGameplayAbility
{
public:
	TMulticastInlineDelegate<void()>              OnApplyPrimaryDamage;                              // 0x2B28(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	void BeginPlay();
	void K2_ActivateAbility();
	void MissileEventNotify();
	void NativeOnMontageCompleted(const class FString& Tag);
	void NativeOnMontageInterrupted(const class FString& Tag);
	void NativeOnMontageCancelled(const class FString& Tag);
	void K2_OnEndAbility(bool bWasCancelled);
	void OnApplyDamage(class AActor* InSource, class AActor* InTarget, const struct FAttributeModifierHandle& ModifierParameterHandle);
	void OnScopeEnd(class AActor* InActor);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyAbility_105321")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyAbility_105321")
	}
	static class UPyAbility_105321* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_105321>();
	}
};

// PythonClass PyAbility_105321.PyBuffAbility_10532101
// 0x0000 (0x1540 - 0x1540)
class UPyBuffAbility_10532101 : public UMarvelSkillEnergyReduceRegenAbility
{
public:
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);
	void OnTagUpdate(const struct FGameplayTag& Tag, bool TagExist);
	void OnOwnerDeath(class AActor* InSource, class AActor* InTarget, const struct FAttributeModifierHandle& ModifierParameterHandle);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyBuffAbility_10532101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyBuffAbility_10532101")
	}
	static class UPyBuffAbility_10532101* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyBuffAbility_10532101>();
	}
};

// PythonClass PyAbility_105321.PyCue_Ability_Loop_10532101
// 0x0010 (0x1240 - 0x1230)
class APyCue_Ability_Loop_10532101 final : public AMarvelCueNotify_Ability
{
public:
	int32                                         EnergyFullAudioID;                                 // 0x1230(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void WhileActiveAudio(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void OnRemoveAudio(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyCue_Ability_Loop_10532101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyCue_Ability_Loop_10532101")
	}
	static class APyCue_Ability_Loop_10532101* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Ability_Loop_10532101>();
	}
};

}

