#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_102472

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_102472.PyUIController_102472
// 0x0000 (0x11F0 - 0x11F0)
class UPyUIController_102472 final : public UUIC_Ability
{
public:
	void OnInit();
	void OnDestruct();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyUIController_102472")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyUIController_102472")
	}
	static class UPyUIController_102472* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyUIController_102472>();
	}
};

// PythonClass PyAbility_102472.PyAbility_102472
// 0x0008 (0x2B30 - 0x2B28)
class UPyAbility_102472 : public UMarvelGameplayAbility
{
public:
	bool                                          IsInAttacking;                                     // 0x2B28(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void BeginPlay();
	bool CanActivate();
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);
	void NativeOnMontageCompleted(const class FString& Tag);
	void NativeOnMontageBlendOut(const class FString& Tag);
	void NativeOnMontageInterrupted(const class FString& Tag);
	void NativeOnMontageCancelled(const class FString& Tag);
	void NativeOnMontageEvent(const class FString& Tag);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyAbility_102472")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyAbility_102472")
	}
	static class UPyAbility_102472* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_102472>();
	}
};

// PythonClass PyAbility_102472.PyCue_ProjectileLoop_10247201
// 0x0000 (0x11A0 - 0x11A0)
class APyCue_ProjectileLoop_10247201 final : public AMarvelCueNotify_Projectile
{
public:
	bool WhileActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyCue_ProjectileLoop_10247201")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyCue_ProjectileLoop_10247201")
	}
	static class APyCue_ProjectileLoop_10247201* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_ProjectileLoop_10247201>();
	}
};

}

