#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_10001201

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_10001201.PyCue_Buff_Loop_10001201
// 0x0000 (0x1750 - 0x1750)
class APyCue_Buff_Loop_10001201 final : public AMarvelCueNotify_Buff
{
public:
	void WhileActiveUI(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void OnRemoveUI(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyCue_Buff_Loop_10001201")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyCue_Buff_Loop_10001201")
	}
	static class APyCue_Buff_Loop_10001201* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Buff_Loop_10001201>();
	}
};

// PythonClass PyAbility_10001201.PyBuffAbility_10001201
// 0x0010 (0x1480 - 0x1470)
class UPyBuffAbility_10001201 : public UMarvelEffectGameplayAbility
{
public:
	TArray<int32>                                 GiftedAbilityIDs;                                  // 0x1470(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, EditConst, NativeAccessSpecifierPublic)

public:
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);
	void OnGiftedAbilityActivate(class UGameplayAbility* ActivatedAbility);
	void OnCooldownTagUpdated(const struct FGameplayTag& TagUpdated, bool TagExists);
	void NextFrameRecoverCD();
	void OnAbilityConsumeCost(class UMarvelGameplayAbility* Ability, float CostValue, const struct FGameplayTag& CostTag);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyBuffAbility_10001201")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyBuffAbility_10001201")
	}
	static class UPyBuffAbility_10001201* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyBuffAbility_10001201>();
	}
};

}

