#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyActor_BattlePass_LinkPoint_Crystal

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// PythonClass PyActor_BattlePass_LinkPoint_Crystal.PyActor_BattlePass_LinkPoint_Crystal
// 0x00D0 (0x07E0 - 0x0710)
class APyActor_BattlePass_LinkPoint_Crystal final : public AActor
{
public:
	uint8                                         Pad_708[0x8];                                      // 0x0708(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class USceneComponent*                        DefaultScene;                                      // 0x0710(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UNiagaraComponent*                      NiagaraComp_Crystal;                               // 0x0718(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UNiagaraComponent*                      NiagaraComp_Foundation;                            // 0x0720(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMarvelWidgetComponent*                 WidgetComp_Crystal;                                // 0x0728(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMarvelWidgetComponent*                 WidgetComp_Regain;                                 // 0x0730(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMarvelWidgetComponent*                 WidgetComp_Interaction;                            // 0x0738(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMap<class FString, bool>                     NiagaraParams_Buy;                                 // 0x0740(0x0050)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	TMap<class FString, bool>                     NiagaraParams_NotBuy;                              // 0x0790(0x0050)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	void ReceiveBeginPlay();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void OnCrystalClicked();
	void OnCrystalHovered();
	void OnCrystalUnhovered();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyActor_BattlePass_LinkPoint_Crystal")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyActor_BattlePass_LinkPoint_Crystal")
	}
	static class APyActor_BattlePass_LinkPoint_Crystal* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyActor_BattlePass_LinkPoint_Crystal>();
	}
};

}

