#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAISubTeamData

#include "Basic.hpp"

#include "PyAIGroupInfoBase_classes.hpp"


namespace SDK
{

// PythonClass PyAISubTeamData.PyAISubTeamData
// 0x0010 (0x0790 - 0x0780)
class APyAISubTeamData : public APyAIGroupInfoBase
{
public:
	TArray<class AMarvelBaseCharacter*>           SubTeamMembers;                                    // 0x0778(0x0010)(Transient, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyAISubTeamData")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyAISubTeamData")
	}
	static class APyAISubTeamData* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyAISubTeamData>();
	}
};

}

