#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyBuffAbility_120_101433

#include "Basic.hpp"

#include "PyBuffAbility_120_101433_classes.hpp"


namespace SDK
{

// PythonFunction PyBuffAbility_120_101433.PyBuffAbility_120_10143302.K2_ActivateAbility
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyBuffAbility_120_10143302::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyBuffAbility_120_10143302", "K2_ActivateAbility");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

