#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyEnergyContestDeboostDoor

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyEnergyContestDeboostDoor.PyEnergyContestDeboostDoor.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct PyEnergyContestDeboostDoor_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndPlayReason;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

