#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyGamemodeAudioMgr

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyGamemodeAudioMgr.PyGamemodeAudioMgr
// 0x0010 (0x08D8 - 0x08C8)
class UPyGamemodeAudioMgr : public UProcedureAudioManager
{
public:
	TMulticastInlineDelegate<void(int32 VoiceId, const class FString& VoiceTag, const class FString& NextVoiceTag)> OnSystemVoiceEnd; // 0x08C8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	void ReceiveInitialize();
	void OnHudInitialize();
	void ReceiveNotifyVoice(const struct FProcedureNotifyDataVoice& DataVoice);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyGamemodeAudioMgr")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyGamemodeAudioMgr")
	}
	static class UPyGamemodeAudioMgr* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyGamemodeAudioMgr>();
	}
};

}

