#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyLevelAnimNodes

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyLevelAnimNodes.PyLevelAnimNodes.GetSkeletalMesh
// 0x0020 (0x0020 - 0x0000)
struct PyLevelAnimNodes_GetSkeletalMesh final
{
public:
	class AActor*                                 Instance;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FString                                 SkeletalMeshName;                                  // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 ReturnValue;                                       // 0x0018(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyLevelAnimNodes.PyLevelAnimNodes.GetMediaPlate
// 0x0020 (0x0020 - 0x0000)
struct PyLevelAnimNodes_GetMediaPlate final
{
public:
	class AActor*                                 Instance;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FString                                 MediaName;                                         // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
	class UMediaPlateComponent*                   ReturnValue;                                       // 0x0018(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyLevelAnimNodes.PyLevelAnimNodes.SpiderZeroFall
// 0x0008 (0x0008 - 0x0000)
struct PyLevelAnimNodes_SpiderZeroFall final
{
public:
	class AActor*                                 Instance;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyLevelAnimNodes.PyLevelAnimNodes.SpiderZeroRandomIdle
// 0x0008 (0x0008 - 0x0000)
struct PyLevelAnimNodes_SpiderZeroRandomIdle final
{
public:
	class AActor*                                 Instance;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyLevelAnimNodes.PyLevelAnimNodes.PlayMediaPlate
// 0x0008 (0x0008 - 0x0000)
struct PyLevelAnimNodes_PlayMediaPlate final
{
public:
	class AActor*                                 Instance;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

}

