#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyM2202AudioComponent

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "MarvelLevel_structs.hpp"
#include "PyAudioItemConfig_classes.hpp"
#include "PyModeAudioComponent_classes.hpp"


namespace SDK
{

// PythonClass PyM2202AudioComponent.PyM2202Galacta
// 0x0000 (0x0710 - 0x0710)
class APyM2202Galacta final : public AActor
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyM2202Galacta")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyM2202Galacta")
	}
	static class APyM2202Galacta* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyM2202Galacta>();
	}
};

// PythonClass PyM2202AudioComponent.PyM2202AudioItem
// 0x0080 (0x0158 - 0x00D8)
class UPyM2202AudioItem final : public UPyLevelModeCommonAudioItem
{
public:
	TArray<struct FLevelAudioContent>             M2202ResultAudio1;                                 // 0x00D8(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             M2202ResultAudio2;                                 // 0x00E8(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             M2202ResultAudio3;                                 // 0x00F8(0x0010)(Edit, NativeAccessSpecifierPublic)
	int32                                         FightStartVoice;                                   // 0x0108(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Remain2MinVoice;                                   // 0x010C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Remain30SecondVoice;                               // 0x0110(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         LeadingVoice;                                      // 0x0114(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         BehindVoice;                                       // 0x0118(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11C[0x4];                                      // 0x011C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAkAudioEvent*                          StartTips_AkEvent;                                 // 0x0120(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          Remain30Second_AkEvent;                            // 0x0128(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          Remain5Second_AkEvent;                             // 0x0130(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          FightEnd_AkEvent;                                  // 0x0138(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          ResultStart_AkEvent;                               // 0x0140(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          ResultSnowSplash_AkEvent;                          // 0x0148(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          ResultSnowStage2_AkEvent;                          // 0x0150(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyM2202AudioItem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyM2202AudioItem")
	}
	static class UPyM2202AudioItem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyM2202AudioItem>();
	}
};

// PythonClass PyM2202AudioComponent.PyM2202AudioComponent
// 0x0000 (0x0120 - 0x0120)
class UPyM2202AudioComponent final : public UPyModeAudioComponent
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyM2202AudioComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyM2202AudioComponent")
	}
	static class UPyM2202AudioComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyM2202AudioComponent>();
	}
};

}

