#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyMarvelGameHUD_M2201

#include "Basic.hpp"

#include "PyMarvelGameHUD_M2201_classes.hpp"
#include "PyMarvelGameHUD_M2201_parameters.hpp"


namespace SDK
{

// PythonFunction PyMarvelGameHUD_M2201.PyMarvelGameHUD_M2201.ReceiveBeginPlay
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void APyMarvelGameHUD_M2201::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyMarvelGameHUD_M2201", "ReceiveBeginPlay");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyMarvelGameHUD_M2201.PyMarvelGameHUD_M2201.ReceiveEndPlay
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// EEndPlayReason                          Reason                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APyMarvelGameHUD_M2201::ReceiveEndPlay(EEndPlayReason Reason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyMarvelGameHUD_M2201", "ReceiveEndPlay");

	Params::PyMarvelGameHUD_M2201_ReceiveEndPlay Parms{};

	Parms.Reason = Reason;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

