#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PySpecialAreaChaosMonitorComponent

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// PythonFunction PySpecialAreaChaosMonitorComponent.PySpecialAreaChaosMonitorComponent.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct PySpecialAreaChaosMonitorComponent_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndPlayReason;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PySpecialAreaChaosMonitorComponent.PySpecialAreaChaosMonitorComponent.OnTriggerBrokenDegreeHandler
// 0x0004 (0x0004 - 0x0000)
struct PySpecialAreaChaosMonitorComponent_OnTriggerBrokenDegreeHandler final
{
public:
	float                                         Degree;                                            // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PySpecialAreaChaosMonitorComponent.PySpecialAreaChaosMonitorComponent.MulticastTrigger
// 0x0004 (0x0004 - 0x0000)
struct PySpecialAreaChaosMonitorComponent_MulticastTrigger final
{
public:
	float                                         Degree;                                            // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

