#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyTotemComponent

#include "Basic.hpp"

#include "PyTotemComponent_classes.hpp"
#include "PyTotemComponent_parameters.hpp"


namespace SDK
{

// PythonFunction PyTotemComponent.PyTotemComponent.ReceiveBeginPlay
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyTotemComponent::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyTotemComponent", "ReceiveBeginPlay");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyTotemComponent.PyTotemComponent.OnRewindForReplay
// (Native, Public, BlueprintCallable)

void UPyTotemComponent::OnRewindForReplay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyTotemComponent", "OnRewindForReplay");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyTotemComponent.PyTotemComponent.OnTick
// (Native, Public, BlueprintCallable)

void UPyTotemComponent::OnTick()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyTotemComponent", "OnTick");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyTotemComponent.PyTotemComponent.ReceiveEndPlay
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPyTotemComponent::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyTotemComponent", "ReceiveEndPlay");

	Params::PyTotemComponent_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyTotemComponent.PyTotemComponent.OnLevelReset
// (Native, Public, BlueprintCallable)

void UPyTotemComponent::OnLevelReset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyTotemComponent", "OnLevelReset");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyTotemComponent.PyTotemComponent.OnMonitorDegreeIncreasing
// (Native, Public, BlueprintCallable)
// Parameters:
// float                                   Degree                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   LastDegree                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   DeltaDegree                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPyTotemComponent::OnMonitorDegreeIncreasing(float Degree, float LastDegree, float DeltaDegree)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyTotemComponent", "OnMonitorDegreeIncreasing");

	Params::PyTotemComponent_OnMonitorDegreeIncreasing Parms{};

	Parms.Degree = Degree;
	Parms.LastDegree = LastDegree;
	Parms.DeltaDegree = DeltaDegree;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyTotemComponent.PyTotemComponent.OnAreaTriggered
// (Native, Public, BlueprintCallable)

void UPyTotemComponent::OnAreaTriggered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyTotemComponent", "OnAreaTriggered");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyTotemComponent.PyTotemComponent.OnAreaStopped
// (Native, Public, BlueprintCallable)

void UPyTotemComponent::OnAreaStopped()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyTotemComponent", "OnAreaStopped");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyTotemComponent.PyTotemComponent.SrvSetTotemTime
// (Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    State                                                  (Parm, ZeroConstructor, HasGetValueTypeHash)
// float                                   Time                                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPyTotemComponent::SrvSetTotemTime(const class FString& State, float Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyTotemComponent", "SrvSetTotemTime");

	Params::PyTotemComponent_SrvSetTotemTime Parms{};

	Parms.State = std::move(State);
	Parms.Time = Time;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyTotemComponent.PyTotemComponent.OnRep_TotemTime
// (Native, Public, BlueprintCallable)

void UPyTotemComponent::OnRep_TotemTime()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyTotemComponent", "OnRep_TotemTime");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyTotemComponent.PyTotemComponent.OnRep_TotemState
// (Native, Public, BlueprintCallable)

void UPyTotemComponent::OnRep_TotemState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyTotemComponent", "OnRep_TotemState");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

