#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Settlement_PersonalData_Qualification

#include "Basic.hpp"

#include "PyWidget_Settlement_PersonalData_New_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Settlement_PersonalData_Qualification.PyWidget_Settlement_PersonalData_Qualification
// 0x0000 (0x05D8 - 0x05D8)
class UPyWidget_Settlement_PersonalData_Qualification final : public UPyWidget_Settlement_PersonalData_Base
{
public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void OnAnimationFinished(const class UWidgetAnimation* Animation);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_Settlement_PersonalData_Qualification")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_Settlement_PersonalData_Qualification")
	}
	static class UPyWidget_Settlement_PersonalData_Qualification* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Settlement_PersonalData_Qualification>();
	}
};

}

