#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Btn_Tips_Base

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Btn_Tips_Base.PyWidget_Btn_Tips_Base
// 0x0010 (0x05E8 - 0x05D8)
class UPyWidget_Btn_Tips_Base : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5D2[0x6];                                      // 0x05D2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              OnActionPerformed;                                 // 0x05D8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_Btn_Tips_Base")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_Btn_Tips_Base")
	}
	static class UPyWidget_Btn_Tips_Base* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Btn_Tips_Base>();
	}
};

// PythonClass PyWidget_Btn_Tips_Base.PyWidget_BtnTipsContainer
// 0x0000 (0x05D8 - 0x05D8)
class UPyWidget_BtnTipsContainer final : public UPyMarvelUserWidget
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_BtnTipsContainer")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_BtnTipsContainer")
	}
	static class UPyWidget_BtnTipsContainer* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_BtnTipsContainer>();
	}
};

// PythonClass PyWidget_Btn_Tips_Base.PyWidget_BtnTips_CheckBox
// 0x0000 (0x05E8 - 0x05E8)
class UPyWidget_BtnTips_CheckBox final : public UPyWidget_Btn_Tips_Base
{
public:
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_BtnTips_CheckBox")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_BtnTips_CheckBox")
	}
	static class UPyWidget_BtnTips_CheckBox* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_BtnTips_CheckBox>();
	}
};

}

