#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Activity160_Main

#include "Basic.hpp"

#include "PyWidget_ModuleMainPanel_classes.hpp"
#include "SlateCore_structs.hpp"
#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Activity160_Main.PyWidget_Activity160_Bg
// 0x0010 (0x0620 - 0x0610)
class UPyWidget_Activity160_Bg final : public UPyWidget_ModuleMainPanel
{
public:
	class UBinkMediaPlayer*                       MainVideoPlayer;                                   // 0x0610(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UBinkMediaPlayer*                       MaskVideoPlayer;                                   // 0x0618(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void OnCascadingVisibleChanged(bool bNewVisible);
	void OnAnimSequance();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_Activity160_Bg")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_Activity160_Bg")
	}
	static class UPyWidget_Activity160_Bg* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Activity160_Bg>();
	}
};

// PythonClass PyWidget_Activity160_Main.PyWidget_Activity160_Main
// 0x0030 (0x0608 - 0x05D8)
class UPyWidget_Activity160_Main final : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5D2[0x2];                                      // 0x05D2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            NormalCountColor;                                  // 0x05D4(0x0014)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FSlateColor                            ExpiringCountColor;                                // 0x05E8(0x0014)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPublic)
	uint8                                         Pad_5FC[0x4];                                      // 0x05FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAkAudioEvent*                          EntryAudio;                                        // 0x0600(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void OnVisibleChanged(bool bNewVisible);
	void OnAnimSequence();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_Activity160_Main")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_Activity160_Main")
	}
	static class UPyWidget_Activity160_Main* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Activity160_Main>();
	}
};

}

