#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Esports_Schedule_DropDownBtn

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_Esports_Schedule_DropDownBtn.PyWidget_Esports_Schedule_DropDownBtn.OnListItemObjectSet
// 0x0008 (0x0008 - 0x0000)
struct PyWidget_Esports_Schedule_DropDownBtn_OnListItemObjectSet final
{
public:
	class UObject*                                _itm;                                              // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_Esports_Schedule_DropDownBtn.PyWidget_Esports_Schedule_DropDownBtn.BP_OnItemExpansionChanged
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_Esports_Schedule_DropDownBtn_BP_OnItemExpansionChanged final
{
public:
	bool                                          is_expanded;                                       // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

