#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_MallRecharge_Main

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_MallRecharge_Main.PyWidget_MallRecharge_Main.OnAnimationFinished
// 0x0008 (0x0008 - 0x0000)
struct PyWidget_MallRecharge_Main_OnAnimationFinished final
{
public:
	const class UWidgetAnimation*                 Animation;                                         // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_MallRecharge_Main.PyWidget_MallRecharge_Main.MarvelSetVisible
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_MallRecharge_Main_MarvelSetVisible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

