#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Activity122_HeroDetailPanel

#include "Basic.hpp"

#include "PyWidget_Activity122_HeroDetailPanel_classes.hpp"
#include "PyWidget_Activity122_HeroDetailPanel_parameters.hpp"


namespace SDK
{

// PythonFunction PyWidget_Activity122_HeroDetailPanel.PyWidget_Activity122_HeroDetailPanel.OnInitialized
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget_Activity122_HeroDetailPanel::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_Activity122_HeroDetailPanel", "OnInitialized");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_Activity122_HeroDetailPanel.PyWidget_Activity122_HeroDetailPanel.PreConstruct
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPyWidget_Activity122_HeroDetailPanel::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_Activity122_HeroDetailPanel", "PreConstruct");

	Params::PyWidget_Activity122_HeroDetailPanel_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_Activity122_HeroDetailPanel.PyWidget_Activity122_HeroDetailPanel.Construct
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget_Activity122_HeroDetailPanel::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_Activity122_HeroDetailPanel", "Construct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_Activity122_HeroDetailPanel.PyWidget_Activity122_HeroDetailPanel.Destruct
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget_Activity122_HeroDetailPanel::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_Activity122_HeroDetailPanel", "Destruct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_Activity122_HeroDetailPanel.PyWidget_Activity122_HeroDetailPanel.OnBecomeTop
// (Native, Protected, BlueprintCallable)

void UPyWidget_Activity122_HeroDetailPanel::OnBecomeTop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_Activity122_HeroDetailPanel", "OnBecomeTop");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_Activity122_HeroDetailPanel.PyWidget_Activity122_HeroDetailPanel.OnBecomeNoneTop
// (Native, Protected, BlueprintCallable)

void UPyWidget_Activity122_HeroDetailPanel::OnBecomeNoneTop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_Activity122_HeroDetailPanel", "OnBecomeNoneTop");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_Activity122_HeroDetailPanel.PyWidget_Activity122_HeroDetailPanel.OnHeroLogoLoaded
// (Native, Public, BlueprintCallable)
// Parameters:
// class UTexture2D*                       Picture                                                (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UPyWidget_Activity122_HeroDetailPanel::OnHeroLogoLoaded(class UTexture2D* Picture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_Activity122_HeroDetailPanel", "OnHeroLogoLoaded");

	Params::PyWidget_Activity122_HeroDetailPanel_OnHeroLogoLoaded Parms{};

	Parms.Picture = Picture;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

