#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_S2_1SeasonStory_Details

#include "Basic.hpp"

#include "PyWidget_S2_1SeasonStory_Details_classes.hpp"
#include "PyWidget_S2_1SeasonStory_Details_parameters.hpp"


namespace SDK
{

// PythonFunction PyWidget_S2_1SeasonStory_Details.PyWidget_S2_1SeasonStory_Details.OnInitialized
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget_S2_1SeasonStory_Details::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_S2_1SeasonStory_Details", "OnInitialized");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_S2_1SeasonStory_Details.PyWidget_S2_1SeasonStory_Details.Construct
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget_S2_1SeasonStory_Details::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_S2_1SeasonStory_Details", "Construct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_S2_1SeasonStory_Details.PyWidget_S2_1SeasonStory_Details.Destruct
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget_S2_1SeasonStory_Details::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_S2_1SeasonStory_Details", "Destruct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_S2_1SeasonStory_Details.PyWidget_S2_1SeasonStory_Details.MarvelSetVisible
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Visible                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPyWidget_S2_1SeasonStory_Details::MarvelSetVisible(bool Visible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_S2_1SeasonStory_Details", "MarvelSetVisible");

	Params::PyWidget_S2_1SeasonStory_Details_MarvelSetVisible Parms{};

	Parms.Visible = Visible;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_S2_1SeasonStory_Details.PyWidget_S2_1SeasonStory_Details_Cipertext.OnInitialized
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget_S2_1SeasonStory_Details_Cipertext::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_S2_1SeasonStory_Details_Cipertext", "OnInitialized");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_S2_1SeasonStory_Details.PyWidget_S2_1SeasonStory_Details_Cipertext.Construct
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget_S2_1SeasonStory_Details_Cipertext::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_S2_1SeasonStory_Details_Cipertext", "Construct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_S2_1SeasonStory_Details.PyWidget_S2_1SeasonStory_Details_Cipertext.Destruct
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget_S2_1SeasonStory_Details_Cipertext::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_S2_1SeasonStory_Details_Cipertext", "Destruct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_S2_1SeasonStory_Details.PyWidget_S2_1SeasonStory_Details_Puzzleb.OnInitialized
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget_S2_1SeasonStory_Details_Puzzleb::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_S2_1SeasonStory_Details_Puzzleb", "OnInitialized");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_S2_1SeasonStory_Details.PyWidget_S2_1SeasonStory_Details_Puzzleb.Destruct
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget_S2_1SeasonStory_Details_Puzzleb::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_S2_1SeasonStory_Details_Puzzleb", "Destruct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_S2_1SeasonStory_Details.PyWidget_S2_1SeasonStory_MainItem.Destruct
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget_S2_1SeasonStory_MainItem::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_S2_1SeasonStory_MainItem", "Destruct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_S2_1SeasonStory_Details.PyWidget_S2_1SeasonStory_MainItem.OnAnimationFinished
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class UWidgetAnimation*           Animation                                              (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UPyWidget_S2_1SeasonStory_MainItem::OnAnimationFinished(const class UWidgetAnimation* Animation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_S2_1SeasonStory_MainItem", "OnAnimationFinished");

	Params::PyWidget_S2_1SeasonStory_MainItem_OnAnimationFinished Parms{};

	Parms.Animation = Animation;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_S2_1SeasonStory_Details.PyWidget_S2_1SeasonStory_MainItem.OnAnimationsDisabled
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget_S2_1SeasonStory_MainItem::OnAnimationsDisabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_S2_1SeasonStory_MainItem", "OnAnimationsDisabled");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_S2_1SeasonStory_Details.PyWidget_S2_1SeasonStory_MainItem.SetItemData
// (Native, Protected, BlueprintCallable)
// Parameters:
// const class FString&                    ItemID_0                                               (Parm, ZeroConstructor, HasGetValueTypeHash)
// EItemType                               ItemType_0                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ItemNum_0                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Multiple                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Small                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    DisableDynamic                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FString&                    ItemUID                                                (Parm, ZeroConstructor, HasGetValueTypeHash)

void UPyWidget_S2_1SeasonStory_MainItem::SetItemData(const class FString& ItemID_0, EItemType ItemType_0, int32 ItemNum_0, int32 Multiple, bool Small, bool DisableDynamic, const class FString& ItemUID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_S2_1SeasonStory_MainItem", "SetItemData");

	Params::PyWidget_S2_1SeasonStory_MainItem_SetItemData Parms{};

	Parms.ItemID_0 = std::move(ItemID_0);
	Parms.ItemType_0 = ItemType_0;
	Parms.ItemNum_0 = ItemNum_0;
	Parms.Multiple = Multiple;
	Parms.Small = Small;
	Parms.DisableDynamic = DisableDynamic;
	Parms.ItemUID = std::move(ItemUID);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_S2_1SeasonStory_Details.PyWidget_S2_1SeasonStory_MainItem.SetIsHover
// (Native, Protected, BlueprintCallable)
// Parameters:
// bool                                    IsHover_0                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPyWidget_S2_1SeasonStory_MainItem::SetIsHover(bool IsHover_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_S2_1SeasonStory_MainItem", "SetIsHover");

	Params::PyWidget_S2_1SeasonStory_MainItem_SetIsHover Parms{};

	Parms.IsHover_0 = IsHover_0;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_S2_1SeasonStory_Details.PyWidget_S2_1SeasonStory_MainItem.SetIsGot
// (Native, Protected, BlueprintCallable)
// Parameters:
// bool                                    IsGot_0                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPyWidget_S2_1SeasonStory_MainItem::SetIsGot(bool IsGot_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_S2_1SeasonStory_MainItem", "SetIsGot");

	Params::PyWidget_S2_1SeasonStory_MainItem_SetIsGot Parms{};

	Parms.IsGot_0 = IsGot_0;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_S2_1SeasonStory_Details.PyWidget_S2_1SeasonStory_MainItem.SetIsLimitTime
// (Native, Protected, BlueprintCallable)
// Parameters:
// bool                                    IsLimitTime_0                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPyWidget_S2_1SeasonStory_MainItem::SetIsLimitTime(bool IsLimitTime_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_S2_1SeasonStory_MainItem", "SetIsLimitTime");

	Params::PyWidget_S2_1SeasonStory_MainItem_SetIsLimitTime Parms{};

	Parms.IsLimitTime_0 = IsLimitTime_0;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_S2_1SeasonStory_Details.PyWidget_S2_1SeasonStory_MainItem.SetItemIconQuality
// (Native, Protected, BlueprintCallable)
// Parameters:
// EItemQualityType                        ItemQuality                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPyWidget_S2_1SeasonStory_MainItem::SetItemIconQuality(EItemQualityType ItemQuality)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_S2_1SeasonStory_MainItem", "SetItemIconQuality");

	Params::PyWidget_S2_1SeasonStory_MainItem_SetItemIconQuality Parms{};

	Parms.ItemQuality = ItemQuality;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

