#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Test_Focus_Unit

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Test_Focus_Unit.PyWidget_Test_Focus_Unit
// 0x0000 (0x0588 - 0x0588)
class UPyWidget_Test_Focus_Unit final : public UWidget_ListEntry
{
public:
	void OnInitialized();
	void OnListItemObjectSet(class UObject* ItemObject);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_Test_Focus_Unit")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_Test_Focus_Unit")
	}
	static class UPyWidget_Test_Focus_Unit* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Test_Focus_Unit>();
	}
};

}

