#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Replay_DownloadButton

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_Replay_DownloadButton.PyWidget_Common_DownloadButton.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_Common_DownloadButton_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

