#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_StoreLottery_Rule

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_StoreLottery_Rule.PyWidget_StoreLottery_Rule.OnCascadingVisibleChanged
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_StoreLottery_Rule_OnCascadingVisibleChanged final
{
public:
	bool                                          bNewVisible;                                       // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

