#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Activity128_Vedio

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Activity128_Vedio.PyWidget_Activity128_Video
// 0x0030 (0x0608 - 0x05D8)
class UPyWidget_Activity128_Video final : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5D2[0x6];                                      // 0x05D2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(const class FString& VideoName)> OnMediaClosed;                    // 0x05D8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	class UMediaPlayer*                           VideoMediaPlayer;                                  // 0x05E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMediaSource*                           FirstMediaSource;                                  // 0x05F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMediaSource*                           DefaultMediaSource;                                // 0x05F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UObject*                                MI_Video;                                          // 0x0600(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_Activity128_Video")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_Activity128_Video")
	}
	static class UPyWidget_Activity128_Video* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Activity128_Video>();
	}
};

}

