#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_PhotoModePanel

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"
#include "PyWidget_ModuleMainPanel_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_PhotoModePanel.PyWidget_PhotoWaterMark
// 0x0000 (0x05D8 - 0x05D8)
class UPyWidget_PhotoWaterMark final : public UPyMarvelUserWidget
{
public:
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_PhotoWaterMark")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_PhotoWaterMark")
	}
	static class UPyWidget_PhotoWaterMark* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_PhotoWaterMark>();
	}
};

// PythonClass PyWidget_PhotoModePanel.PyWidget_PhotoModePanel
// 0x0028 (0x0638 - 0x0610)
class UPyWidget_PhotoModePanel final : public UPyWidget_ModuleMainPanel
{
public:
	TSubclassOf<class APyM2201PhotoCamera>        PhotoCameraClass;                                  // 0x0610(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UInputAction*                           FlyUpAction;                                       // 0x0618(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UInputAction*                           FlyDownAction;                                     // 0x0620(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UInputAction*                           JumpAction;                                        // 0x0628(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          TakePhotoAudio;                                    // 0x0630(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_PhotoModePanel")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_PhotoModePanel")
	}
	static class UPyWidget_PhotoModePanel* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_PhotoModePanel>();
	}
};

}

