#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_LobbyBondPanel

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_LobbyBondPanel.PyWidget_LobbyBond_Card.OnAnimationFinished
// 0x0008 (0x0008 - 0x0000)
struct PyWidget_LobbyBond_Card_OnAnimationFinished final
{
public:
	const class UWidgetAnimation*                 Animation;                                         // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_LobbyBondPanel.PyWidget_LobbyBondPanel.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_LobbyBondPanel_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_LobbyBondPanel.PyWidget_LobbyBondPanel.MarvelSetVisible
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_LobbyBondPanel_MarvelSetVisible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_LobbyBondPanel.PyWidget_LobbyBondPanel.on_try_srcoll_when_next_focusable_child_change
// 0x0018 (0x0018 - 0x0000)
struct PyWidget_LobbyBondPanel_on_try_srcoll_when_next_focusable_child_change final
{
public:
	int32                                         ChildIndex;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         FocusedChildDirection;                             // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         NumItemsLine;                                      // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UButton*                                ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
};

}

