#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Replay_MainPanel

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_Replay_MainPanel.PyWidget_Replay_MainPanel.Tick
// 0x003C (0x003C - 0x0000)
struct PyWidget_Replay_MainPanel_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_Replay_MainPanel.PyWidget_Replay_MainPanel.ShowLoadingPanel
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_Replay_MainPanel_ShowLoadingPanel final
{
public:
	bool                                          Show;                                              // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_Replay_MainPanel.PyWidget_Replay_MainPanel.OnCascadingVisibleChanged
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_Replay_MainPanel_OnCascadingVisibleChanged final
{
public:
	bool                                          bNewVisible;                                       // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

