#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_MallRecharge_Loading

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_MallRecharge_Loading.PyWidget_MallRecharge_Loading.MarvelSetVisible
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_MallRecharge_Loading_MarvelSetVisible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_MallRecharge_Loading.PyWidget_MallRecharge_Loading_Steam_Tips.MarvelSetVisible
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_MallRecharge_Loading_Steam_Tips_MarvelSetVisible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

