#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Activity165_Exp

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Activity165_Exp.WBP_Activity165_Exp_C
// 0x0008 (0x03D0 - 0x03C8)
class UWBP_Activity165_Exp_C final : public UUserWidget
{
public:
	class UMarvelTextBlock*                       Text_Exp;                                          // 0x03C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Activity165_Exp_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Activity165_Exp_C")
	}
	static class UWBP_Activity165_Exp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Activity165_Exp_C>();
	}
};

}

