#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Privilege_NavigationBar_Btn

#include "Basic.hpp"

#include "PyWidget_PrivilegeBtnTip_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Privilege_NavigationBar_Btn.WBP_Privilege_NavigationBar_Btn_C
// 0x0010 (0x0960 - 0x0950)
class UWBP_Privilege_NavigationBar_Btn_C final : public UPyWidget_PrivilegeBtnTip
{
public:
	class UImage*                                 Img_Hover;                                         // 0x0948(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_Normal;                                        // 0x0950(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Privilege_NavigationBar_Btn_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Privilege_NavigationBar_Btn_C")
	}
	static class UWBP_Privilege_NavigationBar_Btn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Privilege_NavigationBar_Btn_C>();
	}
};

}

