#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SecondaryPopupBGPanel

#include "Basic.hpp"

#include "PyWidget_SecondaryPopupBGPanel_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_SecondaryPopupBGPanel.WBP_SecondaryPopupBGPanel_C
// 0x0018 (0x0640 - 0x0628)
class UWBP_SecondaryPopupBGPanel_C final : public UPyWidget_SecondaryPopupBGPanel
{
public:
	class UMarvelOverlay*                         Overlay_BG;                                        // 0x0628(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Common_Panel_A_C*                  WBP_Common_Panel;                                  // 0x0630(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Common_Panel_B_C*                  WBP_Common_Panel_B;                                // 0x0638(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_SecondaryPopupBGPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_SecondaryPopupBGPanel_C")
	}
	static class UWBP_SecondaryPopupBGPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SecondaryPopupBGPanel_C>();
	}
};

}

