#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Deathmatch_SignageTip

#include "Basic.hpp"

#include "PyWidget_DeathMatch_Signage_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Deathmatch_SignageTip.WBP_Deathmatch_SignageTip_C
// 0x0020 (0x05F8 - 0x05D8)
class UWBP_Deathmatch_SignageTip_C final : public UPyWidget_DeathMatch_SignageTips
{
public:
	class UMarvelImage*                           Img_Bg;                                            // 0x05D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_GLow;                                          // 0x05E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Icon;                                          // 0x05E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Vx_Light;                                      // 0x05F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Deathmatch_SignageTip_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Deathmatch_SignageTip_C")
	}
	static class UWBP_Deathmatch_SignageTip_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Deathmatch_SignageTip_C>();
	}
};

}

