#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_106181_BP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Ability_106181_BP.Ability_106181_BP_C
// 0x0000 (0x3448 - 0x3448)
class UAbility_106181_BP_C final : public UMarvelGameplayAbility
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Ability_106181_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Ability_106181_BP_C")
	}
	static class UAbility_106181_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_106181_BP_C>();
	}
};
DUMPER7_ASSERTS_UAbility_106181_BP_C;

SDK_NAMESPACE_END
