#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_106191_BP

#include "Basic.hpp"

#include "PyAbility_106191_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Ability_106191_BP.Ability_106191_BP_C
// 0x0000 (0x3478 - 0x3478)
class UAbility_106191_BP_C final : public UPyAbility_106191
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Ability_106191_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Ability_106191_BP_C")
	}
	static class UAbility_106191_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_106191_BP_C>();
	}
};
DUMPER7_ASSERTS_UAbility_106191_BP_C;

SDK_NAMESPACE_END
