#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BuffAbility_10536102_BP

#include "Basic.hpp"

#include "PyAbility_105361_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BuffAbility_10536102_BP.BuffAbility_10536102_BP_C
// 0x0000 (0x1BF8 - 0x1BF8)
class UBuffAbility_10536102_BP_C final : public UPyBuffAbility_10536102
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BuffAbility_10536102_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BuffAbility_10536102_BP_C")
	}
	static class UBuffAbility_10536102_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBuffAbility_10536102_BP_C>();
	}
};
DUMPER7_ASSERTS_UBuffAbility_10536102_BP_C;

SDK_NAMESPACE_END
