#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EffectiveComponent_10427501_BP

#include "Basic.hpp"

#include "Hero_1042_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass EffectiveComponent_10427501_BP.EffectiveComponent_10427501_BP_C
// 0x0000 (0x2510 - 0x2510)
class UEffectiveComponent_10427501_BP_C final : public UEffectiveComponent_10427501
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("EffectiveComponent_10427501_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EffectiveComponent_10427501_BP_C")
	}
	static class UEffectiveComponent_10427501_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEffectiveComponent_10427501_BP_C>();
	}
};
DUMPER7_ASSERTS_UEffectiveComponent_10427501_BP_C;

SDK_NAMESPACE_END
