#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Hero_1066

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"
#include "StructUtils_structs.hpp"
#include "MarvelAbilityTemplate_classes.hpp"
#include "GameplayTags_structs.hpp"
#include "Engine_structs.hpp"
#include "Hero_1066_structs.hpp"


SDK_NAMESPACE_START

// Class Hero_1066.Config_106601
// 0x0510 (0x05A8 - 0x0098)
class UConfig_106601 : public UMarvelAbilityConfig
{
public:
	int32                                         MaxEnergy;                                         // 0x0098(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         StartEnergy;                                       // 0x009C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         EnhanceEnergy;                                     // 0x00A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         HalfDemonTransformationEnergy;                     // 0x00A4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         LeftMouseAbilityID;                                // 0x00A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         LeftMouseAttackRegen;                              // 0x00AC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FMarvelTraceRule                       LeftMouseHitFilter;                                // 0x00B0(0x04D8)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	int32                                         LeftMouseAttackRegenWithRight;                     // 0x0588(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         RightMouseAbilityID;                               // 0x058C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         RightMouseRegenPerSecond;                          // 0x0590(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         RightMouseRegenPerSecondWithLeft;                  // 0x0594(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RightMouseRegenByAbsorb;                           // 0x0598(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         HalfDemonSpeedBuffID;                              // 0x059C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         HalfDemonTimeBuffID;                               // 0x05A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         HalfDemonVampiricBuffID;                           // 0x05A4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Config_106601")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Config_106601")
	}
	static class UConfig_106601* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConfig_106601>();
	}
};
DUMPER7_ASSERTS_UConfig_106601;

// Class Hero_1066.Ability_106601
// 0x0000 (0x3448 - 0x3448)
class UAbility_106601 : public UMarvelGameplayAbility
{
public:
	bool IsAbilityActiveByID(int32 AbilityID);
	void OnAbilityHit(class UGameplayAbility* InAbility, const struct FMarvelAbilityHitParams& HitParams, const struct FSharedStruct& ReadOnlyHitResultsHolder);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Ability_106601")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Ability_106601")
	}
	static class UAbility_106601* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_106601>();
	}
};
DUMPER7_ASSERTS_UAbility_106601;

// Class Hero_1066.BuffAbility_10660103
// 0x0020 (0x1AF8 - 0x1AD8)
class UBuffAbility_10660103 : public UMarvelEffectGameplayAbility
{
public:
	float                                         ModValue;                                          // 0x1AD8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_1ADC[0x4];                                     // 0x1ADC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FDamageSourceInfo>              DamageSourceInfos;                                 // 0x1AE0(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Protected, NativeAccessSpecifierProtected)
	bool                                          bOnlyTreatFromCharacter;                           // 0x1AF0(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_1AF1[0x3];                                     // 0x1AF1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         ModValueByPenetrateShield;                         // 0x1AF4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	void OnApplyDamage(class AActor* InSourceAvatar, class AActor* InTargetAvatar, const struct FAttributeModifierHandle& ModifierParameterHandle);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("BuffAbility_10660103")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BuffAbility_10660103")
	}
	static class UBuffAbility_10660103* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBuffAbility_10660103>();
	}
};
DUMPER7_ASSERTS_UBuffAbility_10660103;

// Class Hero_1066.Cue_Ability_Loop_10660101
// 0x00A0 (0x14C0 - 0x1420)
class ACue_Ability_Loop_10660101 : public AMarvelCueNotify_Ability
{
public:
	float                                         AbsorptionPlayInterval;                            // 0x1418(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCombineAdsorptionEffect;                          // 0x141C(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_141D[0x3];                                     // 0x141D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraSystem*                         AbsorptionEffect;                                  // 0x1420(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UNiagaraSystem*                         CombineAbsorptionEffect;                           // 0x1428(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FInstancedStruct>               IntParamOps;                                       // 0x1430(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FInstancedStruct>               FloatParamOps;                                     // 0x1440(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FInstancedStruct>               VectorParamOps;                                    // 0x1450(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
	class AActor*                                 OwnerActor;                                        // 0x1460(0x0008)(ZeroConstructor, Transient, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UAbilitySystemComponent*                OwnerASC;                                          // 0x1468(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UNiagaraComponent*                      EnhanceComp;                                       // 0x1470(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bInHalfDemon;                                      // 0x1478(0x0001)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bNeedPlayLoopAudio;                                // 0x1479(0x0001)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bHasTransitionTimer;                               // 0x147A(0x0001)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_147B[0x1];                                     // 0x147B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CurrentVisualRatio;                                // 0x147C(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         LastAbsorptionPlayTime;                            // 0x1480(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FMaterialQuery                         CapeMaterialQuery;                                 // 0x1484(0x0024)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           HalfDemonTag;                                      // 0x14A8(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         EnergyLoopAudio;                                   // 0x14B4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14B8[0x8];                                     // 0x14B8(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void ApplyEnergyVisual(float Ratio);
	void OnSkillEnergyChanged(class AActor* SourceActor, const struct FAttributeModifierHandle& ModifierParameterHandle);
	void RefreshEnergyVisual(float DeltaValue);
	void RefreshLoopAudio(float NowValue, float MaxValue);
	void SetEnhanceComponent(class UNiagaraComponent* InEnhance);
	void SetHasTransitionTimer(bool bInHas);
	void SetInHalfDemon(bool bInExist);
	void SetOwnerCache(class AActor* InOwner, class UAbilitySystemComponent* InOwnerASC);
	void SpawnAbsorptionEffect(class USceneComponent* AttachedComponent);
	void TryPlayAbsorption();

	float GetCurrentVisualRatio() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Cue_Ability_Loop_10660101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Cue_Ability_Loop_10660101")
	}
	static class ACue_Ability_Loop_10660101* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACue_Ability_Loop_10660101>();
	}
};
DUMPER7_ASSERTS_ACue_Ability_Loop_10660101;

// Class Hero_1066.Config_TheHoodFire
// 0x0008 (0x00D0 - 0x00C8)
class UConfig_TheHoodFire : public UConfig_105
{
public:
	bool                                          bEnableAmmoBounce;                                 // 0x00C8(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C9[0x7];                                       // 0x00C9(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Config_TheHoodFire")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Config_TheHoodFire")
	}
	static class UConfig_TheHoodFire* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConfig_TheHoodFire>();
	}
};
DUMPER7_ASSERTS_UConfig_TheHoodFire;

// Class Hero_1066.Config_106611
// 0x0030 (0x0100 - 0x00D0)
class UConfig_106611 final : public UConfig_TheHoodFire
{
public:
	TArray<int32>                                 NormalFireModeIndexes;                             // 0x00D0(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	TArray<int32>                                 EnhanceFireModeIndexes;                            // 0x00E0(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FGameplayTag                           EnhenceTag;                                        // 0x00F0(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_FC[0x4];                                       // 0x00FC(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Config_106611")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Config_106611")
	}
	static class UConfig_106611* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConfig_106611>();
	}
};
DUMPER7_ASSERTS_UConfig_106611;

// Class Hero_1066.InstantAmmo_TheHood
// 0x0000 (0x26E0 - 0x26E0)
class AInstantAmmo_TheHood : public ABounceInstantAmmo
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("InstantAmmo_TheHood")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InstantAmmo_TheHood")
	}
	static class AInstantAmmo_TheHood* GetDefaultObj()
	{
		return GetDefaultObjImpl<AInstantAmmo_TheHood>();
	}
};
DUMPER7_ASSERTS_AInstantAmmo_TheHood;

// Class Hero_1066.Ability_106611
// 0x0000 (0x3548 - 0x3548)
class UAbility_106611 : public UAbility_105
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Ability_106611")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Ability_106611")
	}
	static class UAbility_106611* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_106611>();
	}
};
DUMPER7_ASSERTS_UAbility_106611;

// Class Hero_1066.Cue_Weapon_Loop_106613
// 0x0010 (0x1680 - 0x1670)
class ACue_Weapon_Loop_106613 final : public AMarvelCueNotify_Weapon_Loop
{
public:
	int32                                         MaxClipsCount;                                     // 0x1670(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1674[0xC];                                     // 0x1674(0x000C)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Cue_Weapon_Loop_106613")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Cue_Weapon_Loop_106613")
	}
	static class ACue_Weapon_Loop_106613* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACue_Weapon_Loop_106613>();
	}
};
DUMPER7_ASSERTS_ACue_Weapon_Loop_106613;

// Class Hero_1066.Ability_106641
// 0x0010 (0x3460 - 0x3450)
class UAbility_106641 : public UAbility_108
{
public:
	TMulticastInlineDelegate<void(float ResistChangeNum)> OnResistChangeDelegate;                    // 0x3450(0x0010)(ZeroConstructor, InstancedReference, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Ability_106641")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Ability_106641")
	}
	static class UAbility_106641* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_106641>();
	}
};
DUMPER7_ASSERTS_UAbility_106641;

// Class Hero_1066.Summoned_10664101
// 0x0030 (0x0CB0 - 0x0C80)
class ASummoned_10664101 : public AMarvelBarrierBase
{
public:
	float                                         ShieldResistDamage;                                // 0x0C80(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C84[0x1C];                                     // 0x0C84(0x001C)(Fixing Size After Last Property [ Dumper-7 ])
	class UAbility_106641*                        Ability;                                           // 0x0CA0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_CA8[0x8];                                      // 0x0CA8(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void AddResistDamageByScope(int32 InScopeID);
	void AddResistDamageByValue(const struct FDamageParameter& InBaseDamage, int32 InMaxApplyTimes);
	void CheckResistDamageChange();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Summoned_10664101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Summoned_10664101")
	}
	static class ASummoned_10664101* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASummoned_10664101>();
	}
};
DUMPER7_ASSERTS_ASummoned_10664101;

// Class Hero_1066.Config_106651
// 0x0010 (0x00A8 - 0x0098)
class UConfig_106651 : public UMarvelAbilityConfig
{
public:
	float                                         DamagePercent;                                     // 0x0098(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         TreatPercent;                                      // 0x009C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LeftMouseAttackRegenByPenetrateShield;             // 0x00A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ModValueByPenetrateShield;                         // 0x00A4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Config_106651")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Config_106651")
	}
	static class UConfig_106651* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConfig_106651>();
	}
};
DUMPER7_ASSERTS_UConfig_106651;

// Class Hero_1066.Ability_106651
// 0x0000 (0x3450 - 0x3450)
class UAbility_106651 : public UAbility_108
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Ability_106651")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Ability_106651")
	}
	static class UAbility_106651* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_106651>();
	}
};
DUMPER7_ASSERTS_UAbility_106651;

// Class Hero_1066.Summoned_10665101
// 0x0010 (0x0BF0 - 0x0BE0)
class ASummoned_10665101 : public AMarvelSummonerBase
{
public:
	uint8                                         Pad_BE0[0x10];                                     // 0x0BE0(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Summoned_10665101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Summoned_10665101")
	}
	static class ASummoned_10665101* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASummoned_10665101>();
	}
};
DUMPER7_ASSERTS_ASummoned_10665101;

// Class Hero_1066.ProjectileMovementComponent_10665101
// 0x0000 (0x3410 - 0x3410)
class UProjectileMovementComponent_10665101 final : public UMarvelProjectileComponent
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ProjectileMovementComponent_10665101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ProjectileMovementComponent_10665101")
	}
	static class UProjectileMovementComponent_10665101* GetDefaultObj()
	{
		return GetDefaultObjImpl<UProjectileMovementComponent_10665101>();
	}
};
DUMPER7_ASSERTS_UProjectileMovementComponent_10665101;

// Class Hero_1066.Projectile_10665101
// 0x0000 (0x4580 - 0x4580)
class AProjectile_10665101 : public AMarvelAbilityTargetActor_Projectile
{
public:
	bool IsTargetValidForBounce(const struct FHitResult& InHit);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Projectile_10665101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Projectile_10665101")
	}
	static class AProjectile_10665101* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProjectile_10665101>();
	}
};
DUMPER7_ASSERTS_AProjectile_10665101;

// Class Hero_1066.Cue_Ability_Loop_10666101
// 0x0150 (0x1570 - 0x1420)
class ACue_Ability_Loop_10666101 : public AMarvelCueNotify_Ability
{
public:
	class UMaterialInterface*                     TranslucentOverlayMaterial;                        // 0x1418(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FMaterialParamCopyInfo                 MaterialParamCopyInfo;                             // 0x1420(0x0058)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPublic)
	TArray<struct FMaterialTag>                   ExcludeMaterialTags;                               // 0x1478(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	TArray<struct FMaterialTag>                   EnemyOpacityMaterialTags;                          // 0x1488(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	float                                         EnemyMaterialOpacity;                              // 0x1498(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAffectWeaponMeshes;                               // 0x149C(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_149D[0x3];                                     // 0x149D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         GradientDuration;                                  // 0x14A0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   DissolveParamName;                                 // 0x14A4(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   OverlayInvisibleParamName;                         // 0x14B0(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bRenderCustomDepthPass;                            // 0x14BC(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14BD[0x3];                                     // 0x14BD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AMarvelBaseCharacter*                   OwnerCharacter;                                    // 0x14C0(0x0008)(ZeroConstructor, Transient, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class USkeletalMeshComponent*                 OwningMeshComp;                                    // 0x14C8(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_14D0[0x18];                                    // 0x14D0(0x0018)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class USkeletalMeshComponent*>         WeaponMeshes;                                      // 0x14E8(0x0010)(ExportObject, ZeroConstructor, Transient, ContainsInstancedReference, Protected, NativeAccessSpecifierProtected)
	TArray<class AMarvelCueNotify_Weapon_Loop*>   BoundWeaponCues;                                   // 0x14F8(0x0010)(ZeroConstructor, Transient, Protected, NativeAccessSpecifierProtected)
	TArray<struct FWeaponMeshMaterialCache>       WeaponOriginalMaterials;                           // 0x1508(0x0010)(ZeroConstructor, Transient, ContainsInstancedReference, Protected, NativeAccessSpecifierProtected)
	class UEquipComponent*                        CachedEquipComponent;                              // 0x1518(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FStencilModifier_EnableCustomDepth     EnableCustomDepthModifier;                         // 0x1520(0x0008)(NoDestructor, ContainsInstancedReference, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_1528[0x20];                                    // 0x1528(0x0020)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(EClientPlayerViewSide InViewSide)> ViewSideDelegate;                              // 0x1548(0x0014)(ZeroConstructor, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_155C[0x14];                                    // 0x155C(0x0014)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnChildComponentAttachedForFXHidden(class USceneComponent* CurrentComponent, class USceneComponent* ChildComponent);
	void OnManagedWeaponMaterialChanged(class UActorComponent* InComponent);
	void OnViewSideChanged(EClientPlayerViewSide InViewSide);
	void OnWeaponCuePostAttachRefresh();
	void OnWeaponEquipStateChanged(class AShootingWeapon* Weapon, const struct FMarvelEquipmentTable& WeaponInfo, bool bState);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Cue_Ability_Loop_10666101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Cue_Ability_Loop_10666101")
	}
	static class ACue_Ability_Loop_10666101* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACue_Ability_Loop_10666101>();
	}
};
DUMPER7_ASSERTS_ACue_Ability_Loop_10666101;

// Class Hero_1066.Config_106671
// 0x00F8 (0x01B8 - 0x00C0)
class UConfig_106671 : public UConfig_109
{
public:
	bool                                          bEnableIgnoreFriendlyTrace;                        // 0x00C0(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C1[0x7];                                       // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  IgnoreTraceAssetTags;                              // 0x00C8(0x0068)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPublic)
	TArray<int32>                                 IgnoreTraceFriendlyBuffEffectIDs;                  // 0x0130(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FGameplayTagContainer                  IgnoreTraceFriendlyBuffEffectTags;                 // 0x0140(0x0068)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPublic)
	TArray<int32>                                 WhitelistScopeIDs;                                 // 0x01A8(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Config_106671")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Config_106671")
	}
	static class UConfig_106671* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConfig_106671>();
	}
};
DUMPER7_ASSERTS_UConfig_106671;

// Class Hero_1066.Ability_106671
// 0x0000 (0x3698 - 0x3698)
class UAbility_106671 : public UAbility_109
{
public:
	void OnModifyTreat(const struct FGameplayEffectSpec& Spec, float* InOutTreat, const class UAbilitySystemComponent* SourceASC, const class UAbilitySystemComponent* TargetASC, bool* bModified);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Ability_106671")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Ability_106671")
	}
	static class UAbility_106671* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_106671>();
	}
};
DUMPER7_ASSERTS_UAbility_106671;

// Class Hero_1066.Cue_Scope_HitImpact_10667201
// 0x0008 (0x04B0 - 0x04A8)
class UCue_Scope_HitImpact_10667201 : public UMarvelCueNotify_HitImpact
{
public:
	float                                         FXRadiusRatioToScope;                              // 0x04A8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4AC[0x4];                                      // 0x04AC(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Cue_Scope_HitImpact_10667201")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Cue_Scope_HitImpact_10667201")
	}
	static class UCue_Scope_HitImpact_10667201* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCue_Scope_HitImpact_10667201>();
	}
};
DUMPER7_ASSERTS_UCue_Scope_HitImpact_10667201;

// Class Hero_1066.Config_106672
// 0x0010 (0x00B0 - 0x00A0)
class UConfig_106672 : public UConfig_108
{
public:
	int32                                         ApplyNotTreatShieldScopeID;                        // 0x00A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         NotTreatShieldBuffID;                              // 0x00A4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DamageToShieldPercent;                             // 0x00A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         GuaranteeShield;                                   // 0x00AC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Config_106672")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Config_106672")
	}
	static class UConfig_106672* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConfig_106672>();
	}
};
DUMPER7_ASSERTS_UConfig_106672;

// Class Hero_1066.Ability_106672
// 0x0008 (0x3458 - 0x3450)
class UAbility_106672 : public UAbility_108
{
public:
	float                                         ActiveDamage;                                      // 0x3450(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_3454[0x4];                                     // 0x3454(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void ApplyNotTreatShield();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Ability_106672")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Ability_106672")
	}
	static class UAbility_106672* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_106672>();
	}
};
DUMPER7_ASSERTS_UAbility_106672;

// Class Hero_1066.NotTreatFallAbility_106672
// 0x0078 (0x1E00 - 0x1D88)
class UNotTreatFallAbility_106672 : public UMarvelNotTreatFallAbility
{
public:
	struct FGameplayTag                           UltimateTag;                                       // 0x1D88(0x000C)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1D94[0x4];                                     // 0x1D94(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSet<class UMarvelBaseAbilitySystemComponent*> AttachAbilitySystemComponents;                    // 0x1D98(0x0050)(ExportObject, Transient, ContainsInstancedReference, NativeAccessSpecifierPublic)
	uint8                                         Pad_1DE8[0x18];                                    // 0x1DE8(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void AddShied(class UMarvelBaseAbilitySystemComponent* Source, float Value);
	void OnCharacterEndPlayWithCharacter(class AMarvelBaseCharacter* Target);
	void OnUltimateAbilityTagUpdate(const struct FGameplayTag& Tag, bool Exist);
	void RefreshAttachedAbilitySystemComponents();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("NotTreatFallAbility_106672")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NotTreatFallAbility_106672")
	}
	static class UNotTreatFallAbility_106672* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNotTreatFallAbility_106672>();
	}
};
DUMPER7_ASSERTS_UNotTreatFallAbility_106672;

// Class Hero_1066.TheHoodAnimInstance
// 0x0050 (0x0CC0 - 0x0C70)
class UTheHoodAnimInstance final : public UMarvelAnimInstance
{
public:
	float                                         FireAnimTime;                                      // 0x0C68(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         HalfDemonGroundMotionAnimIndex;                    // 0x0C6C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         HalfDemonAnimOffsetAnimIndex;                      // 0x0C70(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ShieldCloakShow;                                   // 0x0C74(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          FireLeft;                                          // 0x0C75(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          FireRight;                                         // 0x0C76(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C77[0x1];                                      // 0x0C77(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         HalfDemonFireSpeed;                                // 0x0C78(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsHalfDemonState;                                 // 0x0C7C(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSpacewalkStart;                                   // 0x0C7D(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bInSpacewalk;                                      // 0x0C7E(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSpacewalkEnd;                                     // 0x0C7F(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SpacewalkDirection;                                // 0x0C80(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SpacewalkSpeed;                                    // 0x0C84(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         AnimOffsetAnimIndex;                               // 0x0C88(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bIsAcceleration;                                   // 0x0C8C(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_C8D[0x33];                                     // 0x0C8D(0x0033)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("TheHoodAnimInstance")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TheHoodAnimInstance")
	}
	static class UTheHoodAnimInstance* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTheHoodAnimInstance>();
	}
};
DUMPER7_ASSERTS_UTheHoodAnimInstance;

// Class Hero_1066.TheHoodDemonAnimInstance
// 0x0040 (0x0CB0 - 0x0C70)
class UTheHoodDemonAnimInstance final : public UMarvelAnimInstance
{
public:
	bool                                          IsInAir;                                           // 0x0C68(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_C69[0x3];                                      // 0x0C69(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         LookingYawRateLimit;                               // 0x0C6C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         TurnYaw2StopRThreshold;                            // 0x0C70(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         TurnYaw2StopLThreshold;                            // 0x0C74(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         TrunYaw2StopDeltaThreshold;                        // 0x0C78(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         TrunYaw2StopBreakThreshold;                        // 0x0C7C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         TurnBlendSpaceScale;                               // 0x0C80(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         SmoothInterpSpeed;                                 // 0x0C84(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         NoTurnRemainingTimeDelta;                          // 0x0C88(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          Aero_InTurning;                                    // 0x0C8C(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          Aero_Turn2Idle;                                    // 0x0C8D(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          Aero_Stop2Turn;                                    // 0x0C8E(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          Aero_Turn2LStop;                                   // 0x0C8F(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          Aero_Turn2RStop;                                   // 0x0C90(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_C91[0x3];                                      // 0x0C91(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Aero_TurnRate;                                     // 0x0C94(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_C98[0x18];                                     // 0x0C98(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("TheHoodDemonAnimInstance")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TheHoodDemonAnimInstance")
	}
	static class UTheHoodDemonAnimInstance* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTheHoodDemonAnimInstance>();
	}
};
DUMPER7_ASSERTS_UTheHoodDemonAnimInstance;

// Class Hero_1066.TheHoodCharacter
// 0x0000 (0x25C0 - 0x25C0)
class ATheHoodCharacter : public AMarvelBaseCharacter
{
public:
	class UTheHoodMoveLogicBaseComponent*         TheHoodMoveLogic;                                  // 0x25B8(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void SetLivingState(EPlayerLivingState InLivingState);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("TheHoodCharacter")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TheHoodCharacter")
	}
	static class ATheHoodCharacter* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATheHoodCharacter>();
	}
};
DUMPER7_ASSERTS_ATheHoodCharacter;

// Class Hero_1066.TheHoodMoveLogicBaseComponent
// 0x0000 (0x04C8 - 0x04C8)
class UTheHoodMoveLogicBaseComponent final : public UMarvelMoveLogicBaseComponent
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("TheHoodMoveLogicBaseComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TheHoodMoveLogicBaseComponent")
	}
	static class UTheHoodMoveLogicBaseComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTheHoodMoveLogicBaseComponent>();
	}
};
DUMPER7_ASSERTS_UTheHoodMoveLogicBaseComponent;

// Class Hero_1066.TheHoodMovementComponent
// 0x0000 (0x2490 - 0x2490)
class UTheHoodMovementComponent final : public UMarvelCharacterMovementComponent
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("TheHoodMovementComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TheHoodMovementComponent")
	}
	static class UTheHoodMovementComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTheHoodMovementComponent>();
	}
};
DUMPER7_ASSERTS_UTheHoodMovementComponent;

SDK_NAMESPACE_END
