#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: JarvisReplay

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "CoreUObject_classes.hpp"
#include "OnlineSubsystemUtils_classes.hpp"


SDK_NAMESPACE_START

// Class JarvisReplay.JarvisDemoNetConnection
// 0x0000 (0x2900 - 0x2900)
class UJarvisDemoNetConnection final : public UDemoNetConnection
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("JarvisDemoNetConnection")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"JarvisDemoNetConnection")
	}
	static class UJarvisDemoNetConnection* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJarvisDemoNetConnection>();
	}
};
DUMPER7_ASSERTS_UJarvisDemoNetConnection;

// Class JarvisReplay.JarvisReplayCharacter
// 0x0010 (0x0DF0 - 0x0DE0)
class AJarvisReplayCharacter final : public ACharacter
{
public:
	class UInputMappingContext*                   DefaultMappingContext;                             // 0x0DE0(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_DE8[0x8];                                      // 0x0DE8(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("JarvisReplayCharacter")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"JarvisReplayCharacter")
	}
	static class AJarvisReplayCharacter* GetDefaultObj()
	{
		return GetDefaultObjImpl<AJarvisReplayCharacter>();
	}
};
DUMPER7_ASSERTS_AJarvisReplayCharacter;

// Class JarvisReplay.JarvisReplayCharacterInterface
// 0x0000 (0x0000 - 0x0000)
class IJarvisReplayCharacterInterface final : public IInterface
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("JarvisReplayCharacterInterface")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"JarvisReplayCharacterInterface")
	}
	static class IJarvisReplayCharacterInterface* GetDefaultObj()
	{
		return GetDefaultObjImpl<IJarvisReplayCharacterInterface>();
	}
};
DUMPER7_ASSERTS_IJarvisReplayCharacterInterface;

// Class JarvisReplay.JarvisReplayComponent
// 0x0028 (0x0130 - 0x0108)
class UJarvisReplayComponent final : public UActorComponent
{
public:
	uint8                                         Pad_108[0x28];                                     // 0x0108(0x0028)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void PlayRecord();
	void StartRecord();
	void StopRecord();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("JarvisReplayComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"JarvisReplayComponent")
	}
	static class UJarvisReplayComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJarvisReplayComponent>();
	}
};
DUMPER7_ASSERTS_UJarvisReplayComponent;

// Class JarvisReplay.JarvisReplayConnection
// 0x0000 (0x2A20 - 0x2A20)
class UJarvisReplayConnection final : public UIpConnection
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("JarvisReplayConnection")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"JarvisReplayConnection")
	}
	static class UJarvisReplayConnection* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJarvisReplayConnection>();
	}
};
DUMPER7_ASSERTS_UJarvisReplayConnection;

// Class JarvisReplay.JarvisReplayGameInstance
// 0x0000 (0x0460 - 0x0460)
class UJarvisReplayGameInstance final : public UPlatformGameInstance
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("JarvisReplayGameInstance")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"JarvisReplayGameInstance")
	}
	static class UJarvisReplayGameInstance* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJarvisReplayGameInstance>();
	}
};
DUMPER7_ASSERTS_UJarvisReplayGameInstance;

// Class JarvisReplay.JarvisReplayLibrary
// 0x0000 (0x0030 - 0x0030)
class UJarvisReplayLibrary final : public UBlueprintFunctionLibrary
{
public:
	static void RecordInputActionExecutionResult(const class UObject* WCO, bool bExecuted);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("JarvisReplayLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"JarvisReplayLibrary")
	}
	static class UJarvisReplayLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJarvisReplayLibrary>();
	}
};
DUMPER7_ASSERTS_UJarvisReplayLibrary;

// Class JarvisReplay.JarvisReplayNetDriver
// 0x0040 (0x0F10 - 0x0ED0)
class UJarvisReplayNetDriver final : public UIpNetDriver
{
public:
	uint8                                         Pad_ED0[0x40];                                     // 0x0ED0(0x0040)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("JarvisReplayNetDriver")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"JarvisReplayNetDriver")
	}
	static class UJarvisReplayNetDriver* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJarvisReplayNetDriver>();
	}
};
DUMPER7_ASSERTS_UJarvisReplayNetDriver;

// Class JarvisReplay.JarvisReplayPlayerController
// 0x0000 (0x0D70 - 0x0D70)
class AJarvisReplayPlayerController final : public APlayerController
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("JarvisReplayPlayerController")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"JarvisReplayPlayerController")
	}
	static class AJarvisReplayPlayerController* GetDefaultObj()
	{
		return GetDefaultObjImpl<AJarvisReplayPlayerController>();
	}
};
DUMPER7_ASSERTS_AJarvisReplayPlayerController;

// Class JarvisReplay.JarvisReplayDemoNetDriver
// 0x0040 (0x2070 - 0x2030)
class UJarvisReplayDemoNetDriver : public UDemoNetDriver
{
public:
	uint8                                         Pad_2030[0x38];                                    // 0x2030(0x0038)(Fixing Size After Last Property [ Dumper-7 ])
	class UJarvisReplaySubsystem*                 JarvisReplaySubsystem;                             // 0x2068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("JarvisReplayDemoNetDriver")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"JarvisReplayDemoNetDriver")
	}
	static class UJarvisReplayDemoNetDriver* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJarvisReplayDemoNetDriver>();
	}
};
DUMPER7_ASSERTS_UJarvisReplayDemoNetDriver;

// Class JarvisReplay.JarvisReplaySubsystem
// 0x00D8 (0x0138 - 0x0060)
class UJarvisReplaySubsystem final : public UReplaySubsystem
{
public:
	uint8                                         Pad_60[0xD8];                                      // 0x0060(0x00D8)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void LocalRecordJarvisReplay(const class FString& Name_0, const class FString& FriendlyName, const class FString& Options);
	void LocalRecordWidgetEventReplay(const class FString& Name_0, const class FString& FriendlyName, const class FString& Options);
	void PlayJarvisReplay(const class FString& DemoURL, bool bIsNetFile, bool InIsInGameRecord);
	void PlayJarvisReplaySequence(const TArray<class FString>& ReplayIDSequence, int32 InLoopTimes, float InReplayInterval, bool bInQuitAppOnEnd);
	void PlayWidgetEventReplay(const class FString& DemoURL, bool bIsNetFile, bool InIsInGameRecord);
	void RecordJarvisReplay(const class FString& Options, bool bInIsInGameRecord);
	void RecordWidgetEventReplay(const class FString& Options, bool bInIsInGameRecord);

	void CopyReplayIDToClipboard() const;
	float GetRecordingDemoCurrentTime() const;
	class FString GetRecordingReplayID() const;
	bool IsInGameRecord() const;
	bool IsJarvisRecording() const;
	bool IsRecordingWidgetEvent() const;
	void UploadReplayFile() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("JarvisReplaySubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"JarvisReplaySubsystem")
	}
	static class UJarvisReplaySubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJarvisReplaySubsystem>();
	}
};
DUMPER7_ASSERTS_UJarvisReplaySubsystem;

SDK_NAMESPACE_END
