#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NNE

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// Class NNE.NNEModelData
// 0x00E0 (0x0110 - 0x0030)
class UNNEModelData final : public UObject
{
public:
	uint8                                         Pad_30[0xE0];                                      // 0x0030(0x00E0)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("NNEModelData")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NNEModelData")
	}
	static class UNNEModelData* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNNEModelData>();
	}
};
DUMPER7_ASSERTS_UNNEModelData;

// Class NNE.NNERuntime
// 0x0000 (0x0000 - 0x0000)
class INNERuntime final : public IInterface
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("NNERuntime")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NNERuntime")
	}
	static class INNERuntime* GetDefaultObj()
	{
		return GetDefaultObjImpl<INNERuntime>();
	}
};
DUMPER7_ASSERTS_INNERuntime;

// Class NNE.NNERuntimeCPU
// 0x0000 (0x0000 - 0x0000)
class INNERuntimeCPU final : public IInterface
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("NNERuntimeCPU")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NNERuntimeCPU")
	}
	static class INNERuntimeCPU* GetDefaultObj()
	{
		return GetDefaultObjImpl<INNERuntimeCPU>();
	}
};
DUMPER7_ASSERTS_INNERuntimeCPU;

// Class NNE.NNERuntimeGPU
// 0x0000 (0x0000 - 0x0000)
class INNERuntimeGPU final : public IInterface
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("NNERuntimeGPU")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NNERuntimeGPU")
	}
	static class INNERuntimeGPU* GetDefaultObj()
	{
		return GetDefaultObjImpl<INNERuntimeGPU>();
	}
};
DUMPER7_ASSERTS_INNERuntimeGPU;

// Class NNE.NNERuntimeRDG
// 0x0000 (0x0000 - 0x0000)
class INNERuntimeRDG final : public IInterface
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("NNERuntimeRDG")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NNERuntimeRDG")
	}
	static class INNERuntimeRDG* GetDefaultObj()
	{
		return GetDefaultObjImpl<INNERuntimeRDG>();
	}
};
DUMPER7_ASSERTS_INNERuntimeRDG;

SDK_NAMESPACE_END
