#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Projectile_10566101_BP

#include "Basic.hpp"

#include "Hero_1056_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Projectile_10566101_BP.Projectile_10566101_BP_C
// 0x0000 (0x4800 - 0x4800)
class AProjectile_10566101_BP_C final : public AProjectile_10566101
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Projectile_10566101_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Projectile_10566101_BP_C")
	}
	static class AProjectile_10566101_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProjectile_10566101_BP_C>();
	}
};
DUMPER7_ASSERTS_AProjectile_10566101_BP_C;

SDK_NAMESPACE_END
