#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_403831

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Mode_2206_structs.hpp"
#include "Marvel_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyAbility_403831.PySummoned_40383101
// 0x0060 (0x0C40 - 0x0BE0)
class APySummoned_40383101 final : public AMarvelSummonerBase
{
public:
	float                                         MoveSpeed;                                         // 0x0BE0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxStepHeight;                                     // 0x0BE4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxEnemyDetectRange;                               // 0x0BE8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         EnemyDetectInterval;                               // 0x0BEC(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMap<EStormDetectEnemyParam, float>           EnemyDetectParamDict;                              // 0x0BF0(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)

public:
	void K2_OnSummonedBeginAgentTask();
	void K2_OnSummonedEndAgentTask();
	void ReceiveTick(float DeltaSeconds);
	void OnTimeToFindEnemy();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PySummoned_40383101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PySummoned_40383101")
	}
	static class APySummoned_40383101* GetDefaultObj()
	{
		return GetDefaultObjImpl<APySummoned_40383101>();
	}
};
DUMPER7_ASSERTS_APySummoned_40383101;

// PythonClass PyAbility_403831.PySummonedComp_40383101
// 0x0000 (0x1318 - 0x1318)
class UPySummonedComp_40383101 final : public UMarvelSummonedComponent
{
public:
	void K2_OnBeginAgentTask();
	void K2_OnEndAgentTask();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PySummonedComp_40383101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PySummonedComp_40383101")
	}
	static class UPySummonedComp_40383101* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPySummonedComp_40383101>();
	}
};
DUMPER7_ASSERTS_UPySummonedComp_40383101;

// PythonClass PyAbility_403831.PyConfig_403831
// 0x0028 (0x00C0 - 0x0098)
class UPyConfig_403831 final : public UMarvelAbilityConfig
{
public:
	struct FVector                                SummonedSpawnOffset;                               // 0x0098(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SummonedSpawnInterval;                             // 0x00B0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         SummonedInitNum;                                   // 0x00B4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         SummonedDeltaNum;                                  // 0x00B8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         SummonedMaxNum;                                    // 0x00BC(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyConfig_403831")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyConfig_403831")
	}
	static class UPyConfig_403831* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_403831>();
	}
};
DUMPER7_ASSERTS_UPyConfig_403831;

// PythonClass PyAbility_403831.PyAbility_403831
// 0x0000 (0x3448 - 0x3448)
class UPyAbility_403831 final : public UMarvelGameplayAbility
{
public:
	void BeginPlay();
	void EndPlay();
	bool CanActivate();
	void K2_ActivateAbility();
	void MissileEventNotify();
	void K2_OnEndAbility(bool bWasCancelled);
	void NativeOnMontageCompleted(const class FString& Tag);
	void NativeOnMontageEvent(const class FString& Tag);
	void OnTimeToSpawnSummoned();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyAbility_403831")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyAbility_403831")
	}
	static class UPyAbility_403831* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_403831>();
	}
};
DUMPER7_ASSERTS_UPyAbility_403831;

SDK_NAMESPACE_END
