#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_2208_10113201

#include "Basic.hpp"

#include "PyAbility_2208_10113201_classes.hpp"
#include "PyAbility_2208_10113201_parameters.hpp"


SDK_NAMESPACE_START

// PythonFunction PyAbility_2208_10113201.PyPVEScript_2208_10113201.Activate
// (Native, Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AMarvelBaseCharacter*             InCharacter                                            (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FMarvelPVE_EffectSpec&     InPVE_Effect                                           (ConstParm, Parm, OutParm, ReferenceParm)
// const struct FMarvelPVE_CalculationParameters&Parameters                                             (ConstParm, Parm, OutParm, ReferenceParm)

void UPyPVEScript_2208_10113201::Activate(class AMarvelBaseCharacter* InCharacter, const struct FMarvelPVE_EffectSpec& InPVE_Effect, const struct FMarvelPVE_CalculationParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyPVEScript_2208_10113201", "Activate");

	Params::PyPVEScript_2208_10113201_Activate Parms{};

	Parms.InCharacter = InCharacter;
	Parms.InPVE_Effect = std::move(InPVE_Effect);
	Parms.Parameters = std::move(Parameters);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_2208_10113201.PyPVEScript_2208_10113201.OnChanged
// (Native, Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AMarvelBaseCharacter*             Character                                              (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FMarvelPVE_EffectSpec&     PVE_Effect                                             (ConstParm, Parm, OutParm, ReferenceParm)
// const struct FMarvelPVE_CalculationParameters&Parameters                                             (ConstParm, Parm, OutParm, ReferenceParm)

void UPyPVEScript_2208_10113201::OnChanged(class AMarvelBaseCharacter* Character, const struct FMarvelPVE_EffectSpec& PVE_Effect, const struct FMarvelPVE_CalculationParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyPVEScript_2208_10113201", "OnChanged");

	Params::PyPVEScript_2208_10113201_OnChanged Parms{};

	Parms.Character = Character;
	Parms.PVE_Effect = std::move(PVE_Effect);
	Parms.Parameters = std::move(Parameters);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_2208_10113201.PyPVEScript_2208_10113201.End
// (Native, Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AMarvelBaseCharacter*             InCharacter                                            (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FMarvelPVE_EffectSpec&     InPVE_Effect                                           (ConstParm, Parm, OutParm, ReferenceParm)
// const struct FMarvelPVE_CalculationParameters&Parameters                                             (ConstParm, Parm, OutParm, ReferenceParm)

void UPyPVEScript_2208_10113201::End(class AMarvelBaseCharacter* InCharacter, const struct FMarvelPVE_EffectSpec& InPVE_Effect, const struct FMarvelPVE_CalculationParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyPVEScript_2208_10113201", "End");

	Params::PyPVEScript_2208_10113201_End Parms{};

	Parms.InCharacter = InCharacter;
	Parms.InPVE_Effect = std::move(InPVE_Effect);
	Parms.Parameters = std::move(Parameters);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


SDK_NAMESPACE_END
