#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_105912

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// PythonFunction PyAbility_105912.PyAbility_105912.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct PyAbility_105912_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_105912_K2_OnEndAbility;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
