#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_221

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// PythonFunction PyAbility_221.PyAbility_221.SetRefSelectTarget
// 0x0008 (0x0008 - 0x0000)
struct PyAbility_221_SetRefSelectTarget final
{
public:
	class AActor*                                 target;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_221_SetRefSelectTarget;

// PythonFunction PyAbility_221.PyAbility_221.CanActivate
// 0x0001 (0x0001 - 0x0000)
struct PyAbility_221_CanActivate final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_221_CanActivate;

// PythonFunction PyAbility_221.PyAbility_221.CanPreActivate
// 0x0001 (0x0001 - 0x0000)
struct PyAbility_221_CanPreActivate final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_221_CanPreActivate;

// PythonFunction PyAbility_221.PyAbility_221.K2_TriggerGameplay
// 0x0004 (0x0004 - 0x0000)
struct PyAbility_221_K2_TriggerGameplay final
{
public:
	float                                         HoldTime;                                          // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_221_K2_TriggerGameplay;

// PythonFunction PyAbility_221.PyAbility_221.K2_MaxHoldTimeGameplay
// 0x0004 (0x0004 - 0x0000)
struct PyAbility_221_K2_MaxHoldTimeGameplay final
{
public:
	float                                         HoldTime;                                          // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_221_K2_MaxHoldTimeGameplay;

// PythonFunction PyAbility_221.PyAbility_221.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct PyAbility_221_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_221_K2_OnEndAbility;

// PythonFunction PyAbility_221.PyAbility_221.Server_AbilityActivated
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_221_Server_AbilityActivated final
{
public:
	class AActor*                                 InteractedActor;                                   // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AMarvelPlayerState*                     ActivatedPlayerState;                              // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_221_Server_AbilityActivated;

// PythonFunction PyAbility_221.PyAbility_221.Server_AbilityActivated_WithIntParam
// 0x0018 (0x0018 - 0x0000)
struct PyAbility_221_Server_AbilityActivated_WithIntParam final
{
public:
	class AActor*                                 InteractedActor;                                   // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AMarvelPlayerState*                     ActivatedPlayerState;                              // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Param;                                             // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_221_Server_AbilityActivated_WithIntParam;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
