#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_10130_402421

#include "Basic.hpp"

#include "Activity_10130_classes.hpp"
#include "Marvel_structs.hpp"


SDK_NAMESPACE_START

// PythonClass PyAbility_10130_402421.PyProjectile_40242101
// 0x0020 (0x45A0 - 0x4580)
class APyProjectile_40242101 final : public AProjectile_40242101
{
public:
	class UProjectileHomingComponent*             ProjectileHoming;                                  // 0x4580(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnProjectileBounce;                                // 0x4588(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	void K2_OnBeginAgentTask();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyProjectile_40242101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyProjectile_40242101")
	}
	static class APyProjectile_40242101* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyProjectile_40242101>();
	}
};
DUMPER7_ASSERTS_APyProjectile_40242101;

// PythonClass PyAbility_10130_402421.PyConfig_402421
// 0x1D38 (0x1DF0 - 0x00B8)
class UPyConfig_402421 final : public UConfig_402421
{
public:
	uint8                                         Pad_B8[0x8];                                       // 0x00B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSelectTaskParam                       SelectTaskParams;                                  // 0x00C0(0x1D30)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyConfig_402421")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyConfig_402421")
	}
	static class UPyConfig_402421* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_402421>();
	}
};
DUMPER7_ASSERTS_UPyConfig_402421;

// PythonClass PyAbility_10130_402421.PyAbility_402421
// 0x0000 (0x5080 - 0x5080)
class UPyAbility_402421 final : public UAbility_402421
{
public:
	void BeginPlay();
	class AActor* GetSelectTarget(class UMarvelAbilityTask_SelectTarget* SelectTargetTask);
	void K2_ActivateAbility();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyAbility_402421")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyAbility_402421")
	}
	static class UPyAbility_402421* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_402421>();
	}
};
DUMPER7_ASSERTS_UPyAbility_402421;

SDK_NAMESPACE_END
