#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_103591

#include "Basic.hpp"

#include "Hero_1035_classes.hpp"
#include "Marvel_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyAbility_103591.PyConfig_103591
// 0x0020 (0x1CC0 - 0x1CA0)
class UPyConfig_103591 final : public UConfig_103541
{
public:
	int32                                         LoopDamageBuffID;                                  // 0x1CA0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         InstantDamageBuffID;                               // 0x1CA4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         TreatBuffID;                                       // 0x1CA8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LoopDamageHealingRate;                             // 0x1CAC(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         InstantDamageHealingRate;                          // 0x1CB0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyConfig_103591")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyConfig_103591")
	}
	static class UPyConfig_103591* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_103591>();
	}
};
DUMPER7_ASSERTS_UPyConfig_103591;

// PythonClass PyAbility_103591.PyBuffAbility_10359105
// 0x0000 (0x1AD8 - 0x1AD8)
class UPyBuffAbility_10359105 : public UMarvelEffectGameplayAbility
{
public:
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);
	void OnOwnerApplyDamage(class AActor* SourceActor, class AActor* TargetActor, const struct FAttributeModifierHandle& ParameterHandle);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyBuffAbility_10359105")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyBuffAbility_10359105")
	}
	static class UPyBuffAbility_10359105* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyBuffAbility_10359105>();
	}
};
DUMPER7_ASSERTS_UPyBuffAbility_10359105;

SDK_NAMESPACE_END
