#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_106005

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// PythonFunction PyAbility_106005.PyAbility_106005.CanActivate
// 0x0001 (0x0001 - 0x0000)
struct PyAbility_106005_CanActivate final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_106005_CanActivate;

// PythonFunction PyAbility_106005.PyAbility_106005.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct PyAbility_106005_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_106005_K2_OnEndAbility;

// PythonFunction PyAbility_106005.PyAbility_106005.NativeOnMontageCompleted
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_106005_NativeOnMontageCompleted final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_106005_NativeOnMontageCompleted;

// PythonFunction PyAbility_106005.PyAbility_106005.NativeOnMontageBlendOut
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_106005_NativeOnMontageBlendOut final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_106005_NativeOnMontageBlendOut;

// PythonFunction PyAbility_106005.PyAbility_106005.NativeOnMontageInterrupted
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_106005_NativeOnMontageInterrupted final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_106005_NativeOnMontageInterrupted;

// PythonFunction PyAbility_106005.PyAbility_106005.NativeOnMontageCancelled
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_106005_NativeOnMontageCancelled final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_106005_NativeOnMontageCancelled;

// PythonFunction PyAbility_106005.PyAbility_106005.NativeOnMontageEvent
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_106005_NativeOnMontageEvent final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_106005_NativeOnMontageEvent;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
