#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_101161

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "GameplayAbilities_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// PythonFunction PyAbility_101161.PyAbility_101161.OnBlockJumpTagChanged
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_101161_OnBlockJumpTagChanged final
{
public:
	struct FGameplayTag                           Tag;                                               // 0x0000(0x000C)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)
	bool                                          Exist;                                             // 0x000C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_101161_OnBlockJumpTagChanged;

// PythonFunction PyAbility_101161.PyAbility_101161.CanActivate
// 0x0001 (0x0001 - 0x0000)
struct PyAbility_101161_CanActivate final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_101161_CanActivate;

// PythonFunction PyAbility_101161.PyAbility_101161.TryMakeTriggerContext
// 0x0298 (0x0298 - 0x0000)
struct PyAbility_101161_TryMakeTriggerContext final
{
public:
	struct FGameplayEventData                     EventData;                                         // 0x0000(0x0290)(Parm, OutParm, ReferenceParm)
	bool                                          ReturnValue;                                       // 0x0290(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_101161_TryMakeTriggerContext;

// PythonFunction PyAbility_101161.PyAbility_101161.K2_ActivateAbilityFromEvent
// 0x0290 (0x0290 - 0x0000)
struct PyAbility_101161_K2_ActivateAbilityFromEvent final
{
public:
	struct FGameplayEventData                     EventData;                                         // 0x0000(0x0290)(ConstParm, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PyAbility_101161_K2_ActivateAbilityFromEvent;

// PythonFunction PyAbility_101161.PyAbility_101161.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct PyAbility_101161_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_101161_K2_OnEndAbility;

// PythonFunction PyAbility_101161.PyAbility_101161.NativeOnMontageEvent
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_101161_NativeOnMontageEvent final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_101161_NativeOnMontageEvent;

// PythonFunction PyAbility_101161.PyAbility_101161.OnLaunched
// 0x0020 (0x0020 - 0x0000)
struct PyAbility_101161_OnLaunched final
{
public:
	struct FVector                                LaunchVelocity;                                    // 0x0000(0x0018)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bXYOverride;                                       // 0x0018(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bZOverride;                                        // 0x0019(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_101161_OnLaunched;

// PythonFunction PyAbility_101161.PyAbility_101161.OnMovementModeChanged
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_101161_OnMovementModeChanged final
{
public:
	class ACharacter*                             MyCharacter;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EMovementMode                                 PrevMode;                                          // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CustomMode;                                        // 0x0009(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_101161_OnMovementModeChanged;

// PythonFunction PyAbility_101161.PyAbility_101161.OnShiftJumpTagUpdated
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_101161_OnShiftJumpTagUpdated final
{
public:
	struct FGameplayTag                           Tag;                                               // 0x0000(0x000C)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)
	bool                                          Exist;                                             // 0x000C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_101161_OnShiftJumpTagUpdated;

// PythonFunction PyAbility_101161.PyAbility_101161.NativeOnMontageCompleted
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_101161_NativeOnMontageCompleted final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_101161_NativeOnMontageCompleted;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
