#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_102003

#include "Basic.hpp"

#include "Marvel_classes.hpp"
#include "PyAbility_134_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyAbility_102003.PyConfig_102003
// 0x0000 (0x0280 - 0x0280)
class UPyConfig_102003 final : public UPyConfig_134
{
public:
	bool                                          bForceEnterCooldown;                               // 0x0279(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyConfig_102003")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyConfig_102003")
	}
	static class UPyConfig_102003* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_102003>();
	}
};
DUMPER7_ASSERTS_UPyConfig_102003;

// PythonClass PyAbility_102003.PyAbility_102003
// 0x0000 (0x3700 - 0x3700)
class UPyAbility_102003 : public UPyAbility_134
{
public:
	void BeginPlay();
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyAbility_102003")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyAbility_102003")
	}
	static class UPyAbility_102003* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_102003>();
	}
};
DUMPER7_ASSERTS_UPyAbility_102003;

// PythonClass PyAbility_102003.PyCue_Scope_Loop_10200301
// 0x0000 (0x1310 - 0x1310)
class APyCue_Scope_Loop_10200301 final : public AMarvelCueNotify_Scope
{
public:
	void WhileActiveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void OnRemoveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyCue_Scope_Loop_10200301")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyCue_Scope_Loop_10200301")
	}
	static class APyCue_Scope_Loop_10200301* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Scope_Loop_10200301>();
	}
};
DUMPER7_ASSERTS_APyCue_Scope_Loop_10200301;

SDK_NAMESPACE_END
