#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_104392

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"
#include "PyAbility_104331_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyAbility_104392.PyConfig_104392
// 0x0030 (0x0128 - 0x00F8)
class UPyConfig_104392 final : public UConfig_AeroBase
{
public:
	bool                                          RefreshCDAfterKill;                                // 0x00F8(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_F9[0x3];                                       // 0x00F9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         AbilityId;                                         // 0x00FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FStateChangedTaskParam                 AbilityActiveUserSetting;                          // 0x0100(0x0028)(Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyConfig_104392")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyConfig_104392")
	}
	static class UPyConfig_104392* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_104392>();
	}
};
DUMPER7_ASSERTS_UPyConfig_104392;

// PythonClass PyAbility_104392.PyAbility_104392
// 0x0000 (0x35E0 - 0x35E0)
class UPyAbility_104392 final : public UPyAbility_104331
{
public:
	void K2_ActivateAbility();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyAbility_104392")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyAbility_104392")
	}
	static class UPyAbility_104392* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_104392>();
	}
};
DUMPER7_ASSERTS_UPyAbility_104392;

SDK_NAMESPACE_END
