#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_102563

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayAbilities_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// PythonFunction PyAbility_102563.PyCueNotify_TakeDamage_10256301.OnExecuteAudio
// 0x0358 (0x0358 - 0x0000)
struct PyCueNotify_TakeDamage_10256301_OnExecuteAudio final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x0350)(ConstParm, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PyCueNotify_TakeDamage_10256301_OnExecuteAudio;

// PythonFunction PyAbility_102563.PyScope_10256301.K2_OnQuoteSourceEndTask
// 0x0008 (0x0008 - 0x0000)
struct PyScope_10256301_K2_OnQuoteSourceEndTask final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyScope_10256301_K2_OnQuoteSourceEndTask;

// PythonFunction PyAbility_102563.PySummoned_10256301.OnActorPenetrate
// 0x0218 (0x0218 - 0x0000)
struct PySummoned_10256301_OnActorPenetrate final
{
public:
	struct FHitResult                             ImpactResult;                                      // 0x0000(0x0210)(ConstParm, Parm, OutParm, ReferenceParm)
	class AActor*                                 Target;                                            // 0x0210(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PySummoned_10256301_OnActorPenetrate;

// PythonFunction PyAbility_102563.PyCue_Scope_Loop_10256301.OnActiveFX
// 0x0358 (0x0358 - 0x0000)
struct PyCue_Scope_Loop_10256301_OnActiveFX final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x0350)(ConstParm, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PyCue_Scope_Loop_10256301_OnActiveFX;

// PythonFunction PyAbility_102563.PyCue_Scope_Loop_10256301.OnRemoveFX
// 0x0358 (0x0358 - 0x0000)
struct PyCue_Scope_Loop_10256301_OnRemoveFX final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x0350)(ConstParm, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PyCue_Scope_Loop_10256301_OnRemoveFX;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
