#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_407539

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"
#include "GameplayTags_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// PythonFunction PyAbility_407539.PyAbility_407539.K2_ActivateAbilityFromEvent
// 0x0290 (0x0290 - 0x0000)
struct PyAbility_407539_K2_ActivateAbilityFromEvent final
{
public:
	struct FGameplayEventData                     EventData;                                         // 0x0000(0x0290)(ConstParm, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PyAbility_407539_K2_ActivateAbilityFromEvent;

// PythonFunction PyAbility_407539.PyAbility_407539.NativeOnMontageEvent
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_407539_NativeOnMontageEvent final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_407539_NativeOnMontageEvent;

// PythonFunction PyAbility_407539.PyAbility_407539.NativeOnMontageCompleted
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_407539_NativeOnMontageCompleted final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_407539_NativeOnMontageCompleted;

// PythonFunction PyAbility_407539.PyAbility_407539.NativeOnMontageInterrupted
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_407539_NativeOnMontageInterrupted final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_407539_NativeOnMontageInterrupted;

// PythonFunction PyAbility_407539.PyAbility_407539.NativeOnMontageCancelled
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_407539_NativeOnMontageCancelled final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_407539_NativeOnMontageCancelled;

// PythonFunction PyAbility_407539.PyAbility_407539.K2_CanActivateAbility
// 0x00D0 (0x00D0 - 0x0000)
struct PyAbility_407539_K2_CanActivateAbility final
{
public:
	struct FGameplayAbilityActorInfo              ActorInfo;                                         // 0x0000(0x0058)(Parm)
	struct FGameplayAbilitySpecHandle             Handle;                                            // 0x0058(0x0004)(ConstParm, Parm, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  RelevantTags;                                      // 0x0060(0x0068)(Parm, OutParm)
	bool                                          ReturnValue;                                       // 0x00C8(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_407539_K2_CanActivateAbility;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
