#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_120_10321121

#include "Basic.hpp"

#include "Marvel_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyAbility_120_10321121.PyBuffAbility_120_10321121
// 0x0010 (0x1AE8 - 0x1AD8)
class UPyBuffAbility_120_10321121 final : public UMarvelEffectGameplayAbility
{
public:
	float                                         DoubleShootRatio;                                  // 0x1AD8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DoubleShootDelay;                                  // 0x1ADC(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ProjectileID;                                      // 0x1AE0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void K2_ActivateAbility();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyBuffAbility_120_10321121")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyBuffAbility_120_10321121")
	}
	static class UPyBuffAbility_120_10321121* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyBuffAbility_120_10321121>();
	}
};
DUMPER7_ASSERTS_UPyBuffAbility_120_10321121;

SDK_NAMESPACE_END
