#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_105662

#include "Basic.hpp"

#include "MarvelAbilityTemplate_classes.hpp"
#include "Hero_1056_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyAbility_105662.PyConfig_105662
// 0x0010 (0x2D20 - 0x2D10)
class UPyConfig_105662 final : public UConfig_105662
{
public:
	float                                         GroundExploreDist;                                 // 0x2D10(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         GroundScopeID;                                     // 0x2D14(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyConfig_105662")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyConfig_105662")
	}
	static class UPyConfig_105662* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_105662>();
	}
};
DUMPER7_ASSERTS_UPyConfig_105662;

// PythonClass PyAbility_105662.PyConfig_105663
// 0x0000 (0x1E20 - 0x1E20)
class UPyConfig_105663 final : public UMarvelLaunchToCharacterConfig
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyConfig_105663")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyConfig_105663")
	}
	static class UPyConfig_105663* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_105663>();
	}
};
DUMPER7_ASSERTS_UPyConfig_105663;

// PythonClass PyAbility_105662.PyAbility_105662
// 0x0000 (0x3578 - 0x3578)
class UPyAbility_105662 : public UAbility_105662
{
public:
	int32 GetTimelineIndexToPlay();
	void BeginPlay();
	void MissileEventNotify();
	void NativeOnMontageEvent(const class FString& EventTag);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyAbility_105662")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyAbility_105662")
	}
	static class UPyAbility_105662* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_105662>();
	}
};
DUMPER7_ASSERTS_UPyAbility_105662;

// PythonClass PyAbility_105662.PyAbility_105663
// 0x0000 (0x37D0 - 0x37D0)
class UPyAbility_105663 final : public UMarvelLaunchToCharacterAbility
{
public:
	void BeginPlay();
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData);
	int32 GetTimelineIndexToPlay();
	void InternalEndMovement();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyAbility_105663")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyAbility_105663")
	}
	static class UPyAbility_105663* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_105663>();
	}
};
DUMPER7_ASSERTS_UPyAbility_105663;

SDK_NAMESPACE_END
