#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_10130_104494

#include "Basic.hpp"

#include "Activity_10130_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyAbility_10130_104494.PyConfig_10130_104494
// 0x0010 (0x1EA0 - 0x1E90)
class UPyConfig_10130_104494 final : public UConfig_10130_104494
{
public:
	float                                         CircleTime;                                        // 0x1E90(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         CircleTimeFast;                                    // 0x1E94(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         FlyProjectileID;                                   // 0x1E98(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         RotateProjectileID;                                // 0x1E9C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyConfig_10130_104494")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyConfig_10130_104494")
	}
	static class UPyConfig_10130_104494* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_10130_104494>();
	}
};
DUMPER7_ASSERTS_UPyConfig_10130_104494;

// PythonClass PyAbility_10130_104494.PyAbility_10130_104494
// 0x0000 (0x34F0 - 0x34F0)
class UPyAbility_10130_104494 : public UAbility_10130_104494
{
public:
	void K2_ActivateAbility();
	void TryCreateProjectile();
	void CreateProjectileWithInfo(const struct FMarvelAbilitySocketInfo& SocketInfo, int32 MergeCnt);
	void SetBD1(bool is_bd1);
	void LimitRotateProjNum(int32 MaxProjNum);
	void SetRotateSpeedBoost(bool enable);
	void StartMoveOut(float OutwardTime, float IntervalTime, int32 RepeatTime);
	void SetData();
	void RemoveFromArr(class AActor* Projectile);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyAbility_10130_104494")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyAbility_10130_104494")
	}
	static class UPyAbility_10130_104494* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_10130_104494>();
	}
};
DUMPER7_ASSERTS_UPyAbility_10130_104494;

// PythonClass PyAbility_10130_104494.PyProjectile_10130_10449491
// 0x0000 (0x45A0 - 0x45A0)
class APyProjectile_10130_10449491 : public AProjectile_10130_10449491
{
public:
	void RemoveFromOwner();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyProjectile_10130_10449491")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyProjectile_10130_10449491")
	}
	static class APyProjectile_10130_10449491* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyProjectile_10130_10449491>();
	}
};
DUMPER7_ASSERTS_APyProjectile_10130_10449491;

SDK_NAMESPACE_END
