#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_106171

#include "Basic.hpp"

#include "MarvelAbilityTemplate_classes.hpp"
#include "GameplayTags_structs.hpp"
#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "MarvelGameplayCues_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyAbility_106171.PyCueNotify_Buff_Loop_10617104
// 0x0050 (0x13F0 - 0x13A0)
class APyCueNotify_Buff_Loop_10617104 final : public AMarvelCueNotify_FX_Trajectory
{
public:
	uint8                                         Pad_1398[0x8];                                     // 0x1398(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraSystem*                         HitLoopFX;                                         // 0x13A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 HitLoopAttachName;                                 // 0x13A8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                HitLoopLocationOffset;                             // 0x13B8(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator                               HitLoopRotation;                                   // 0x13D0(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)

public:
	bool WhileActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void OnTrajectoryFXEnd();
	bool OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void GameplayCueFinishedCallback();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyCueNotify_Buff_Loop_10617104")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyCueNotify_Buff_Loop_10617104")
	}
	static class APyCueNotify_Buff_Loop_10617104* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCueNotify_Buff_Loop_10617104>();
	}
};
DUMPER7_ASSERTS_APyCueNotify_Buff_Loop_10617104;

// PythonClass PyAbility_106171.PyConfig_106171
// 0x0108 (0x01A0 - 0x0098)
class UPyConfig_106171 final : public UMarvelAbilityConfig
{
public:
	bool                                          IsAssistRefreshCD;                                 // 0x0098(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_99[0x3];                                       // 0x0099(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         PhaseTwoBuffID;                                    // 0x009C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PhaseThreeBuffID;                                  // 0x00A0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         RefreshDurationBuffID;                             // 0x00A4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PerspectiveMarkBuffID;                             // 0x00A8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           TriggerRefreshCueTag;                              // 0x00AC(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AddDurationOnKill;                                 // 0x00B8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         SpawnProjectileID;                                 // 0x00BC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FMarvelAbilitySocketInfo               SpawnSocketInfo;                                   // 0x00C0(0x00A0)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	struct FGameplayTag                           PickTag;                                           // 0x0160(0x000C)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_16C[0x4];                                      // 0x016C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                SpawnOffset;                                       // 0x0170(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 TargetBone;                                        // 0x0188(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxProjectileDistance;                             // 0x0198(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyConfig_106171")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyConfig_106171")
	}
	static class UPyConfig_106171* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_106171>();
	}
};
DUMPER7_ASSERTS_UPyConfig_106171;

// PythonClass PyAbility_106171.PyProjectile_10617101
// 0x0010 (0x4590 - 0x4580)
class APyProjectile_10617101 final : public AMarvelAbilityTargetActor_Projectile
{
public:
	uint8                                         Pad_4578[0x8];                                     // 0x4578(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UProjectileHomingComponent*             ProjectileHoming;                                  // 0x4580(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void K2_OnBeginAgentTask();
	void K2_OnEndAgentTask();
	void Tick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyProjectile_10617101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyProjectile_10617101")
	}
	static class APyProjectile_10617101* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyProjectile_10617101>();
	}
};
DUMPER7_ASSERTS_APyProjectile_10617101;

// PythonClass PyAbility_106171.PyAbility_106171
// 0x0000 (0x3450 - 0x3450)
class UPyAbility_106171 : public UAbility_108
{
public:
	void BeginPlay();
	void K2_ActivateAbility();
	void OnAbilityActivate(int32 AbilityID);
	void K2_OnEndAbility(bool bWasCancelled);
	void OnSpawnCharacter(class AMarvelBaseCharacter* NewChar, ESpawnMethod SpawnMode);
	void ClientRefreshPhaseTwoAbility();
	void AddPhaseTwoBuff();
	void MissileEventNotify();
	void K2_EndAbilityWithChecked();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyAbility_106171")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyAbility_106171")
	}
	static class UPyAbility_106171* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_106171>();
	}
};
DUMPER7_ASSERTS_UPyAbility_106171;

SDK_NAMESPACE_END
