#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_106651

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "GameplayAbilities_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// PythonFunction PyAbility_106651.PyProjectile_10665101.K2_OnProjectileInfoForceChanged_ThreadSafe
// 0x0300 (0x0300 - 0x0000)
struct PyProjectile_10665101_K2_OnProjectileInfoForceChanged_ThreadSafe final
{
public:
	struct FProjectileForceChangedInfo            ChangedInfo;                                       // 0x0000(0x0300)(ConstParm, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PyProjectile_10665101_K2_OnProjectileInfoForceChanged_ThreadSafe;

// PythonFunction PyAbility_106651.PyProjectile_10665101.K2_OnBounce
// 0x0228 (0x0228 - 0x0000)
struct PyProjectile_10665101_K2_OnBounce final
{
public:
	struct FHitResult                             ImpactResult;                                      // 0x0000(0x0210)(ConstParm, Parm, OutParm, ReferenceParm)
	struct FVector                                ImpactVelocity;                                    // 0x0210(0x0018)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyProjectile_10665101_K2_OnBounce;

// PythonFunction PyAbility_106651.PyProjectile_10665101.K2_OnProcessHit
// 0x0210 (0x0210 - 0x0000)
struct PyProjectile_10665101_K2_OnProcessHit final
{
public:
	struct FHitResult                             ImpactResult;                                      // 0x0000(0x0210)(ConstParm, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PyProjectile_10665101_K2_OnProcessHit;

// PythonFunction PyAbility_106651.PyProjectile_10665101.SpawnSummoned
// 0x00B0 (0x00B0 - 0x0000)
struct PyProjectile_10665101_SpawnSummoned final
{
public:
	struct FMarvelAbilitySocketInfo               socket_info;                                       // 0x0000(0x00A0)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor)
	int32                                         spawn_type;                                        // 0x00A0(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyProjectile_10665101_SpawnSummoned;

// PythonFunction PyAbility_106651.PyProjectile_10665101.InitSummoned
// 0x0008 (0x0008 - 0x0000)
struct PyProjectile_10665101_InitSummoned final
{
public:
	class AActor*                                 Source;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyProjectile_10665101_InitSummoned;

// PythonFunction PyAbility_106651.PyProjectile_10665101.IsTargetValidForBounce
// 0x0218 (0x0218 - 0x0000)
struct PyProjectile_10665101_IsTargetValidForBounce final
{
public:
	struct FHitResult                             ImpactResult;                                      // 0x0000(0x0210)(ConstParm, Parm, OutParm, ReferenceParm)
	bool                                          ReturnValue;                                       // 0x0210(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyProjectile_10665101_IsTargetValidForBounce;

// PythonFunction PyAbility_106651.PyAbility_106651.CanActivate
// 0x0001 (0x0001 - 0x0000)
struct PyAbility_106651_CanActivate final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_106651_CanActivate;

// PythonFunction PyAbility_106651.PyAbility_106651.OnProjectileSpawnSuccess
// 0x0008 (0x0008 - 0x0000)
struct PyAbility_106651_OnProjectileSpawnSuccess final
{
public:
	class AActor*                                 SpawnActor;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_106651_OnProjectileSpawnSuccess;

// PythonFunction PyAbility_106651.PyAbility_106651.OnWaitTaskConfirm
// 0x0004 (0x0004 - 0x0000)
struct PyAbility_106651_OnWaitTaskConfirm final
{
public:
	float                                         TimeWaited;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_106651_OnWaitTaskConfirm;

// PythonFunction PyAbility_106651.PyAbility_106651.OnProjectileReflect
// 0x0300 (0x0300 - 0x0000)
struct PyAbility_106651_OnProjectileReflect final
{
public:
	struct FProjectileForceChangedInfo            ChangedInfo;                                       // 0x0000(0x0300)(ConstParm, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PyAbility_106651_OnProjectileReflect;

// PythonFunction PyAbility_106651.PyAbility_106651.OnProjectileEnd
// 0x0008 (0x0008 - 0x0000)
struct PyAbility_106651_OnProjectileEnd final
{
public:
	class AActor*                                 InActor;                                           // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_106651_OnProjectileEnd;

// PythonFunction PyAbility_106651.PyAbility_106651.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct PyAbility_106651_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_106651_K2_OnEndAbility;

// PythonFunction PyAbility_106651.PyAbility_106651.GetTimelineIndexToPlay
// 0x0004 (0x0004 - 0x0000)
struct PyAbility_106651_GetTimelineIndexToPlay final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyAbility_106651_GetTimelineIndexToPlay;

// PythonFunction PyAbility_106651.PyOverlapHandler_10665101.ApplyEffectOnEnemyOverlap
// 0x0008 (0x0008 - 0x0000)
struct PyOverlapHandler_10665101_ApplyEffectOnEnemyOverlap final
{
public:
	class AActor*                                 InActor;                                           // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyOverlapHandler_10665101_ApplyEffectOnEnemyOverlap;

// PythonFunction PyAbility_106651.PySummoned_10665101.OnActorPenetrate
// 0x0218 (0x0218 - 0x0000)
struct PySummoned_10665101_OnActorPenetrate final
{
public:
	struct FHitResult                             ImpactResult;                                      // 0x0000(0x0210)(ConstParm, Parm, OutParm, ReferenceParm)
	class AActor*                                 Target;                                            // 0x0210(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PySummoned_10665101_OnActorPenetrate;

// PythonFunction PyAbility_106651.PySummoned_10665101.GetDamagedCueName
// 0x0010 (0x0010 - 0x0000)
struct PySummoned_10665101_GetDamagedCueName final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PySummoned_10665101_GetDamagedCueName;

// PythonFunction PyAbility_106651.PyCueNotify_TakeDamage_10665101.OnExecuteAudio
// 0x0358 (0x0358 - 0x0000)
struct PyCueNotify_TakeDamage_10665101_OnExecuteAudio final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x0350)(ConstParm, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PyCueNotify_TakeDamage_10665101_OnExecuteAudio;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
