#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_102341

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"
#include "Hero_1023_structs.hpp"
#include "Hero_1023_classes.hpp"
#include "MarvelAbilityTemplate_classes.hpp"
#include "GameplayTags_structs.hpp"


SDK_NAMESPACE_START

// PythonClass PyAbility_102341.PyConfig_102341
// 0x3778 (0x3820 - 0x00A8)
class UPyConfig_102341 : public UConfig_102341
{
public:
	struct FVector                                SpawnOffset;                                       // 0x00A8(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxLifetime_Flying;                                // 0x00C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxLifetime_Unactive;                              // 0x00C4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ActiveDelay;                                       // 0x00C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ProjectileSpeed;                                   // 0x00CC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ProjectileGravityScale;                            // 0x00D0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ManualDestroyMaxCooldown;                          // 0x00D4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D8[0x8];                                       // 0x00D8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMarvelAbilityTraceContext             ThrowTraceContext;                                 // 0x00E0(0x1B70)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	int32                                         SpawnSummonedID;                                   // 0x1C50(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RespawnPeriod_Respawning;                          // 0x1C54(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Respawning_CameraLength;                           // 0x1C58(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Respawning_CameraRestoreSpeed;                     // 0x1C5C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Respawning_CameraOffset;                           // 0x1C60(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Respawning_CameraOffsetRestoreSpeed;               // 0x1C78(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C7C[0x4];                                     // 0x1C7C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMarvelAbilityTraceContext             RespawnValidSpaceTraceParam;                       // 0x1C80(0x1B70)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	int32                                         ResurrectPriority;                                 // 0x37F0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_37F4[0x4];                                     // 0x37F4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<ESummonedType_102341>                  SpawnItemSequence;                                 // 0x37F8(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	float                                         SpawnItemInterval;                                 // 0x3808(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SpawnItemDeltaDegrees;                             // 0x380C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SpawnItemPitch;                                    // 0x3810(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SpawnItemSpeed;                                    // 0x3814(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SpawnUpTraceLength;                                // 0x3818(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          DebugRespawnSelf;                                  // 0x381C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          DebugRespawnEnemy;                                 // 0x381D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          DebugSpawnFailed;                                  // 0x381E(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyConfig_102341")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyConfig_102341")
	}
	static class UPyConfig_102341* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_102341>();
	}
};
DUMPER7_ASSERTS_UPyConfig_102341;

// PythonClass PyAbility_102341.PyCue_Buff_10234107
// 0x00E0 (0x1AB0 - 0x19D0)
class APyCue_Buff_10234107 final : public ACue_Buff_10234107
{
public:
	struct FWidgetStyle_BattleTransientTip        ResurrectTip;                                      // 0x19D0(0x0048)(Edit, NativeAccessSpecifierPublic)
	struct FWidgetStyle_BattleTransientTip        ResurrectFailedTip;                                // 0x1A18(0x0048)(Edit, NativeAccessSpecifierPublic)
	struct FWidgetStyle_BattlePersistentTip       ResurrectingTip;                                   // 0x1A60(0x0048)(Edit, NativeAccessSpecifierPublic)

public:
	bool WhileActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void OnResurrectStateChanged(class USummonedComp_10234101* summoned_comp, ESpawnState old_state, ESpawnState new_state);
	bool OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyCue_Buff_10234107")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyCue_Buff_10234107")
	}
	static class APyCue_Buff_10234107* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Buff_10234107>();
	}
};
DUMPER7_ASSERTS_APyCue_Buff_10234107;

// PythonClass PyAbility_102341.PySummonedComp_102341_Item
// 0x0008 (0x1320 - 0x1318)
class UPySummonedComp_102341_Item : public UMarvelSummonedComponent
{
public:
	bool                                          IsLanded;                                          // 0x1318(0x0001)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsArmorPack;                                       // 0x1319(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsRocketShoes;                                     // 0x131A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void K2_OnBeginAgentTask();
	void K2_OnEndAgentTask();
	void K2_OnRecycleAgentTask();
	void OnProjectileStop(const struct FHitResult& ImpactResult);
	void OnServerLand();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PySummonedComp_102341_Item")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PySummonedComp_102341_Item")
	}
	static class UPySummonedComp_102341_Item* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPySummonedComp_102341_Item>();
	}
};
DUMPER7_ASSERTS_UPySummonedComp_102341_Item;

// PythonClass PyAbility_102341.PySummoned_10234101_RespawnerManager
// 0x0000 (0x0030 - 0x0030)
class UPySummoned_10234101_RespawnerManager final : public UObject
{
public:
	bool TryResurrectCharacter(class AActor* DeadActor);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PySummoned_10234101_RespawnerManager")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PySummoned_10234101_RespawnerManager")
	}
	static class UPySummoned_10234101_RespawnerManager* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPySummoned_10234101_RespawnerManager>();
	}
};
DUMPER7_ASSERTS_UPySummoned_10234101_RespawnerManager;

// PythonClass PyAbility_102341.PySummoned_102341_Item
// 0x0030 (0x0C50 - 0x0C20)
#pragma pack(push, 0x1)
class SDK_ALIGN(0x10) APySummoned_102341_Item : public ASummoned_10234101_Item
{
public:
	bool                                          IsArmorPack;                                       // 0x0C20(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsRocketShoes;                                     // 0x0C21(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C22[0x6];                                      // 0x0C22(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                InitialVelocity;                                   // 0x0C28(0x0018)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Launched;                                          // 0x0C40(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PySummoned_102341_Item")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PySummoned_102341_Item")
	}
	static class APySummoned_102341_Item* GetDefaultObj()
	{
		return GetDefaultObjImpl<APySummoned_102341_Item>();
	}
};
#pragma pack(pop)
DUMPER7_ASSERTS_APySummoned_102341_Item;

// PythonClass PyAbility_102341.PySummonedComp_10234101
// 0x0020 (0x1370 - 0x1350)
class UPySummonedComp_10234101 : public USummonedComp_10234101
{
public:
	float                                         RespawningCharacterHeight;                         // 0x1350(0x0004)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SpawnItemActiveTime;                               // 0x1354(0x0004)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DelayDestroyTime;                                  // 0x1358(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_135C[0x4];                                     // 0x135C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              OnSpawnItemSuccess;                                // 0x1360(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	void K2_OnBeginAgentTask();
	void OnCharacterDead(class AActor* DamageCauser, class AActor* TargetActor, const struct FAttributeModifierHandle& ModifierHandle);
	void Launch(const struct FVector& summoned_location, const struct FVector& aim_location);
	void SyncSummonedVelocityWhileFlying();
	void Multicast_VelocityWhileFlying(const struct FVector& Velocity, const struct FVector& Pos);
	void DelayEndSummoned();
	void DoEndSummonedAfterDelay();
	void OnProjectileStop(const struct FHitResult& hit);
	void MulticastProjectileStop(const struct FTransform& ServerTransform);
	void OnCheckValidSpace();
	void K2_OnEndAgentTask();
	void K2_OnRecycleAgentTask();
	void MulticastStartRespawn(class AMarvelPlayerState* ps, class AMarvelBaseCharacter* char_0);
	bool IsLeaveTimerValid();
	void ClearLeaveTimer();
	void OnReachMaximumInactiveTime();
	void enter_pre_resurrect_state();
	void enter_resurrect_finish_state();
	void SpawnItem();
	void OnSpawnItem(class AActor* Item);
	void NetMulticast_SpawnedItemSuccess();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PySummonedComp_10234101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PySummonedComp_10234101")
	}
	static class UPySummonedComp_10234101* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPySummonedComp_10234101>();
	}
};
DUMPER7_ASSERTS_UPySummonedComp_10234101;

// PythonClass PyAbility_102341.PyCue_Summoner_Loop_10234101_2
// 0x0030 (0x15C0 - 0x1590)
class APyCue_Summoner_Loop_10234101_2 final : public ACue_Summoner_Loop_10234101_2
{
public:
	int32                                         DisappearAudioID;                                  // 0x1590(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         DestroyedAudioID;                                  // 0x1594(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                UpMeshRelativeLocation;                            // 0x1598(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnTopDisappearStart;                               // 0x15B0(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	bool WhileActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	bool OnExecute(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	bool OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void OnExecuteAudio(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void OnCueStateChanged(class USummonedComp_10234101* SummonedComponnet, ESpawnState OldState, ESpawnState NewState);
	void OnSpawnItemSuccess();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyCue_Summoner_Loop_10234101_2")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyCue_Summoner_Loop_10234101_2")
	}
	static class APyCue_Summoner_Loop_10234101_2* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Summoner_Loop_10234101_2>();
	}
};
DUMPER7_ASSERTS_APyCue_Summoner_Loop_10234101_2;

// PythonClass PyAbility_102341.PyAbility_102341
// 0x0070 (0x34C0 - 0x3450)
class UPyAbility_102341 : public UAbility_108
{
public:
	class UPySummonedComp_10234101*               CurrentSummonedComp;                               // 0x3450(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, ZeroConstructor, EditConst, InstancedReference, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTagContainer                  AbilityMainTag;                                    // 0x3458(0x0068)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	void BeginPlay();
	bool CanActivate();
	void OnCharacterReborn(class AActor* TargetActor, const struct FCharacterRebornParam& Param);
	void K2_ActivateAbility();
	void MissileEventNotify();
	void SpawnSummoned();
	void OnSummonedStateChanged(class USummonedComp_10234101* summoned_comp, ESpawnState old_state, ESpawnState new_state);
	void OnRep_CurrentSummonedComp();
	void K2_OnEndAbility(bool bWasCancelled);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyAbility_102341")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyAbility_102341")
	}
	static class UPyAbility_102341* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_102341>();
	}
};
DUMPER7_ASSERTS_UPyAbility_102341;

// PythonClass PyAbility_102341.Py_Scope_10234101
// 0x0000 (0x1E70 - 0x1E70)
class APy_Scope_10234101 final : public AMarvelAbilityTargetActor_Scope
{
public:
	void K2_OnBeginAgentTask();
	void K2_OnEndAgentTask();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Py_Scope_10234101")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Py_Scope_10234101")
	}
	static class APy_Scope_10234101* GetDefaultObj()
	{
		return GetDefaultObjImpl<APy_Scope_10234101>();
	}
};
DUMPER7_ASSERTS_APy_Scope_10234101;

// PythonClass PyAbility_102341.PyResurrectionAbility_102341
// 0x0000 (0x1B78 - 0x1B78)
class UPyResurrectionAbility_102341 : public UResurrectionAbility_102341
{
public:
	void K2_OnEndAbility(bool bWasCancelled);
	void K2_OnRep_ResurrectionState();
	void OnAbilityDestroy();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyResurrectionAbility_102341")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyResurrectionAbility_102341")
	}
	static class UPyResurrectionAbility_102341* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyResurrectionAbility_102341>();
	}
};
DUMPER7_ASSERTS_UPyResurrectionAbility_102341;

SDK_NAMESPACE_END
