#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_101633

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "Marvel_structs.hpp"
#include "PyAbility_101651_classes.hpp"
#include "Hero_1016_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyAbility_101633.PyConfig_101633
// 0x1B90 (0x38E0 - 0x1D50)
class UPyConfig_101633 final : public UConfig_101651
{
public:
	struct FGameplayTag                           PawnPlacementCueTag;                               // 0x1D50(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           PawnPlacementCueTag_802;                           // 0x1D5C(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         PhantomHeight;                                     // 0x1D68(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1D6C[0x4];                                     // 0x1D6C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMarvelAbilityTraceContext             PhantomTraceContext;                               // 0x1D70(0x1B70)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyConfig_101633")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyConfig_101633")
	}
	static class UPyConfig_101633* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_101633>();
	}
};
DUMPER7_ASSERTS_UPyConfig_101633;

// PythonClass PyAbility_101633.PyAbility_101633
// 0x0000 (0x34D8 - 0x34D8)
class UPyAbility_101633 : public UPyAbility_101651
{
public:
	bool ShouldTickUpdateTimelineTask() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyAbility_101633")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyAbility_101633")
	}
	static class UPyAbility_101633* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_101633>();
	}
};
DUMPER7_ASSERTS_UPyAbility_101633;

SDK_NAMESPACE_END
