#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyBuffAbility_120_10362180

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyBuffAbility_120_10362180.PyBuffAbility_120_10362180
// 0x0150 (0x1C28 - 0x1AD8)
class UPyBuffAbility_120_10362180 final : public UMarvelEffectGameplayAbility
{
public:
	float                                         EnergyRegenValueIcrement;                          // 0x1AD8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1ADC[0x4];                                     // 0x1ADC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMarvelBuffSpecInfo                    WebBoundBuffSpecInfo;                              // 0x1AE0(0x0148)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPublic)

public:
	void K2_ActivateAbility();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyBuffAbility_120_10362180")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyBuffAbility_120_10362180")
	}
	static class UPyBuffAbility_120_10362180* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyBuffAbility_120_10362180>();
	}
};
DUMPER7_ASSERTS_UPyBuffAbility_120_10362180;

SDK_NAMESPACE_END
