#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyBuffAbility_2206_103951

#include "Basic.hpp"

#include "Marvel_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// PythonFunction PyBuffAbility_2206_103951.PyPVEScript_2206_10397104.Activate
// 0x0070 (0x0070 - 0x0000)
struct PyPVEScript_2206_10397104_Activate final
{
public:
	class AMarvelBaseCharacter*                   InCharacter;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FMarvelPVE_EffectSpec                  InPVE_Effect;                                      // 0x0008(0x0048)(ConstParm, Parm, OutParm, ReferenceParm)
	struct FMarvelPVE_CalculationParameters       Parameters;                                        // 0x0050(0x0020)(ConstParm, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PyPVEScript_2206_10397104_Activate;

// PythonFunction PyBuffAbility_2206_103951.PyPVEScript_2206_10397104.OnChanged
// 0x0070 (0x0070 - 0x0000)
struct PyPVEScript_2206_10397104_OnChanged final
{
public:
	class AMarvelBaseCharacter*                   Character;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FMarvelPVE_EffectSpec                  PVE_Effect;                                        // 0x0008(0x0048)(ConstParm, Parm, OutParm, ReferenceParm)
	struct FMarvelPVE_CalculationParameters       Parameters;                                        // 0x0050(0x0020)(ConstParm, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PyPVEScript_2206_10397104_OnChanged;

// PythonFunction PyBuffAbility_2206_103951.PyPVEScript_2206_10397104.End
// 0x0070 (0x0070 - 0x0000)
struct PyPVEScript_2206_10397104_End final
{
public:
	class AMarvelBaseCharacter*                   InCharacter;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FMarvelPVE_EffectSpec                  InPVE_Effect;                                      // 0x0008(0x0048)(ConstParm, Parm, OutParm, ReferenceParm)
	struct FMarvelPVE_CalculationParameters       Parameters;                                        // 0x0050(0x0020)(ConstParm, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PyPVEScript_2206_10397104_End;

// PythonFunction PyBuffAbility_2206_103951.PyPVEScript_2206_10397104.OnEffectApplied
// 0x00D0 (0x00D0 - 0x0000)
struct PyPVEScript_2206_10397104_OnEffectApplied final
{
public:
	class AMarvelBaseCharacter*                   Character;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FMarvelPVE_EffectSpec_Special          EffectSpec;                                        // 0x0008(0x00B0)(ConstParm, Parm, OutParm, ReferenceParm)
	struct FMarvelPVE_ActiveEffectHandle          Handle;                                            // 0x00B8(0x0018)(ConstParm, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PyPVEScript_2206_10397104_OnEffectApplied;

// PythonFunction PyBuffAbility_2206_103951.PyPVEScript_2206_10397101.Activate
// 0x0070 (0x0070 - 0x0000)
struct PyPVEScript_2206_10397101_Activate final
{
public:
	class AMarvelBaseCharacter*                   InCharacter;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FMarvelPVE_EffectSpec                  InPVE_Effect;                                      // 0x0008(0x0048)(ConstParm, Parm, OutParm, ReferenceParm)
	struct FMarvelPVE_CalculationParameters       Parameters;                                        // 0x0050(0x0020)(ConstParm, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PyPVEScript_2206_10397101_Activate;

// PythonFunction PyBuffAbility_2206_103951.PyPVEScript_2206_10397101.OnChanged
// 0x0070 (0x0070 - 0x0000)
struct PyPVEScript_2206_10397101_OnChanged final
{
public:
	class AMarvelBaseCharacter*                   Character;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FMarvelPVE_EffectSpec                  PVE_Effect;                                        // 0x0008(0x0048)(ConstParm, Parm, OutParm, ReferenceParm)
	struct FMarvelPVE_CalculationParameters       Parameters;                                        // 0x0050(0x0020)(ConstParm, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PyPVEScript_2206_10397101_OnChanged;

// PythonFunction PyBuffAbility_2206_103951.PyPVEScript_2206_10397101.End
// 0x0070 (0x0070 - 0x0000)
struct PyPVEScript_2206_10397101_End final
{
public:
	class AMarvelBaseCharacter*                   InCharacter;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FMarvelPVE_EffectSpec                  InPVE_Effect;                                      // 0x0008(0x0048)(ConstParm, Parm, OutParm, ReferenceParm)
	struct FMarvelPVE_CalculationParameters       Parameters;                                        // 0x0050(0x0020)(ConstParm, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PyPVEScript_2206_10397101_End;

// PythonFunction PyBuffAbility_2206_103951.PyBuffAbility_2206_10397013.OnTargetAbilitySpawnedProjectile
// 0x0008 (0x0008 - 0x0000)
struct PyBuffAbility_2206_10397013_OnTargetAbilitySpawnedProjectile final
{
public:
	class AActor*                                 Projectile;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyBuffAbility_2206_10397013_OnTargetAbilitySpawnedProjectile;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
