#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyBuffAbility_120_DamageSource

#include "Basic.hpp"

#include "Marvel_classes.hpp"
#include "GameplayTags_structs.hpp"


SDK_NAMESPACE_START

// PythonClass PyBuffAbility_120_DamageSource.PyBuffAbility_120_DamageSource
// 0x0008 (0x1AE0 - 0x1AD8)
class UPyBuffAbility_120_DamageSource final : public UMarvelStackCountChangeAbility
{
public:
	int32                                         DamageSourceBuffID;                                // 0x1AD8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         TakeDamageThreshold;                               // 0x1ADC(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);
	void OnTakeDamage(class AActor* InSourceAvatar, class AActor* InTargetAvatar, const struct FAttributeModifierHandle& ModifierParameterHandle);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyBuffAbility_120_DamageSource")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyBuffAbility_120_DamageSource")
	}
	static class UPyBuffAbility_120_DamageSource* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyBuffAbility_120_DamageSource>();
	}
};
DUMPER7_ASSERTS_UPyBuffAbility_120_DamageSource;

// PythonClass PyBuffAbility_120_DamageSource.PyBuffAbility_IgnoreSourceDamagePercent
// 0x0078 (0x1B50 - 0x1AD8)
class UPyBuffAbility_IgnoreSourceDamagePercent final : public UMarvelEffectGameplayAbility
{
public:
	TArray<int32>                                 ScopeIDs;                                          // 0x1AD8(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FGameplayTagContainer                  DamageAssetTags;                                   // 0x1AE8(0x0068)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPublic)

public:
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyBuffAbility_IgnoreSourceDamagePercent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyBuffAbility_IgnoreSourceDamagePercent")
	}
	static class UPyBuffAbility_IgnoreSourceDamagePercent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyBuffAbility_IgnoreSourceDamagePercent>();
	}
};
DUMPER7_ASSERTS_UPyBuffAbility_IgnoreSourceDamagePercent;

SDK_NAMESPACE_END
