#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyBuffAbility_120_101431

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"
#include "Marvel_structs.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// PythonFunction PyBuffAbility_120_101431.PyBuffAbility_120_10143180.OnGameplayEffectStackChange
// 0x0010 (0x0010 - 0x0000)
struct PyBuffAbility_120_10143180_OnGameplayEffectStackChange final
{
public:
	struct FActiveGameplayEffectHandle            Handle;                                            // 0x0000(0x0008)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)
	int32                                         NewCount;                                          // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         OldCount;                                          // 0x000C(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyBuffAbility_120_10143180_OnGameplayEffectStackChange;

// PythonFunction PyBuffAbility_120_101431.PyBuffAbility_120_10143181.OnCreateFireTask
// 0x0008 (0x0008 - 0x0000)
struct PyBuffAbility_120_10143181_OnCreateFireTask final
{
public:
	class UMarvelWeaponTask_Firing*               FireTask;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyBuffAbility_120_10143181_OnCreateFireTask;

// PythonFunction PyBuffAbility_120_101431.PyBuffAbility_120_10143181.ChangeFireDirection
// 0x0080 (0x0080 - 0x0000)
struct PyBuffAbility_120_10143181_ChangeFireDirection final
{
public:
	struct FVector                                muzzle_location;                                   // 0x0000(0x0018)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                ori_direction;                                     // 0x0018(0x0018)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         mode_index;                                        // 0x0030(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCustomFireTraceData                   ReturnValue;                                       // 0x0038(0x0048)(Parm, OutParm, ReturnParm)
};
DUMPER7_ASSERTS_PyBuffAbility_120_10143181_ChangeFireDirection;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
