#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyBuffAbility_220102

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "Mode_2201_classes.hpp"
#include "Marvel_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyBuffAbility_220102.PyBuffAbility_220102
// 0x0018 (0x1BA8 - 0x1B90)
class UPyBuffAbility_220102 : public UBuffAbility_BodySizeChange
{
public:
	int32                                         BanAbilityBuffID;                                  // 0x1B90(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ImmobilizationBuffID;                              // 0x1B94(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         HiddenTime;                                        // 0x1B98(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           RideTag;                                           // 0x1B9C(0x000C)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);
	void K2_OnBodySizeCameraChanged();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyBuffAbility_220102")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyBuffAbility_220102")
	}
	static class UPyBuffAbility_220102* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyBuffAbility_220102>();
	}
};
DUMPER7_ASSERTS_UPyBuffAbility_220102;

// PythonClass PyBuffAbility_220102.PyCue_Buff_220102
// 0x0070 (0x1A70 - 0x1A00)
class APyCue_Buff_220102 final : public ACue_Buff_22010201
{
public:
	class FString                                 SpecialSocketName;                                 // 0x1A00(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<int32>                                 SpecialSocketList;                                 // 0x1A10(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	float                                         BaseHalfHeight;                                    // 0x1A20(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1A24[0x4];                                     // 0x1A24(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAkAudioEvent*                          BigStartAudio_AkEvent;                             // 0x1A28(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          BigEndAudio_AkEvent;                               // 0x1A30(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          BigCountDownAudio_AkEvent;                         // 0x1A38(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          SmallStartAudio_AkEvent;                           // 0x1A40(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          SmallEndAudio_AkEvent;                             // 0x1A48(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          SmallCountDownAudio_AkEvent;                       // 0x1A50(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AudioCountDownTime;                                // 0x1A58(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ClearAfterImageTime;                               // 0x1A5C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BuffDuration;                                      // 0x1A60(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           RideTag;                                           // 0x1A64(0x000C)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void WhileActiveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void WhileActiveAudio(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void OnRemoveAudio(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	bool OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyCue_Buff_220102")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyCue_Buff_220102")
	}
	static class APyCue_Buff_220102* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Buff_220102>();
	}
};
DUMPER7_ASSERTS_APyCue_Buff_220102;

SDK_NAMESPACE_END
