#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyCue_Buff_Loop_10000025

#include "Basic.hpp"

#include "Marvel_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyCue_Buff_Loop_10000025.PyCue_Buff_Loop_10000025
// 0x0010 (0x1950 - 0x1940)
class APyCue_Buff_Loop_10000025 final : public AMarvelCueNotify_Buff
{
public:
	uint8                                         Pad_1938[0x8];                                     // 0x1938(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UAkAudioEvent*                          TeleportAudio;                                     // 0x1940(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnActiveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	bool OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyCue_Buff_Loop_10000025")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyCue_Buff_Loop_10000025")
	}
	static class APyCue_Buff_Loop_10000025* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Buff_Loop_10000025>();
	}
};
DUMPER7_ASSERTS_APyCue_Buff_Loop_10000025;

SDK_NAMESPACE_END
