#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyExtension_ShowItem_Preview

#include "Basic.hpp"

#include "PyExtension_ShowItemBase_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyExtension_ShowItem_Preview.PyExtension_ShowItem_Preview
// 0x0000 (0x0030 - 0x0030)
class UPyExtension_ShowItem_Preview final : public UPyExtension_ShowItemBase
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyExtension_ShowItem_Preview")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyExtension_ShowItem_Preview")
	}
	static class UPyExtension_ShowItem_Preview* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyExtension_ShowItem_Preview>();
	}
};
DUMPER7_ASSERTS_UPyExtension_ShowItem_Preview;

SDK_NAMESPACE_END
