#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyExtension_LayerWidgetEntry

#include "Basic.hpp"

#include "Marvel_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyExtension_LayerWidgetEntry.PyExtension_LayerWidgetEntry
// 0x0020 (0x0050 - 0x0030)
class UPyExtension_LayerWidgetEntry : public UMarvelUserWidgetExtension
{
public:
	TMulticastInlineDelegate<void()>              OnIsValidFullScreenChanged;                        // 0x0030(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnIsValidExclusiveInputChanged;                    // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	void BP_OnInitialize();
	void BP_OnVisibleChanged(bool bNewVisible);
	void BP_OnCascadingVisibleChanged(bool bNewVisible);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyExtension_LayerWidgetEntry")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyExtension_LayerWidgetEntry")
	}
	static class UPyExtension_LayerWidgetEntry* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyExtension_LayerWidgetEntry>();
	}
};
DUMPER7_ASSERTS_UPyExtension_LayerWidgetEntry;

SDK_NAMESPACE_END
