#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyKrakoaPortalScreenFX

#include "Basic.hpp"

#include "Marvel_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyKrakoaPortalScreenFX.PyWidget_ScreenFX_KrakoaPortal_Teleportation
// 0x0028 (0x05C8 - 0x05A0)
class UPyWidget_ScreenFX_KrakoaPortal_Teleportation final : public UMarvelUserWidget
{
public:
	class UMarvelCanvasPanel*                     Panel_Blue;                                        // 0x05A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMarvelCanvasPanel*                     Panel_Darkblue;                                    // 0x05A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMarvelCanvasPanel*                     Panel_Green;                                       // 0x05B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMarvelCanvasPanel*                     Panel_Purple;                                      // 0x05B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMarvelCanvasPanel*                     Panel_Gold;                                        // 0x05C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void Construct();
	void MarvelSetVisible(bool bInExist);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_ScreenFX_KrakoaPortal_Teleportation")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_ScreenFX_KrakoaPortal_Teleportation")
	}
	static class UPyWidget_ScreenFX_KrakoaPortal_Teleportation* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_ScreenFX_KrakoaPortal_Teleportation>();
	}
};
DUMPER7_ASSERTS_UPyWidget_ScreenFX_KrakoaPortal_Teleportation;

SDK_NAMESPACE_END
