#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyLevelLootManager

#include "Basic.hpp"

#include "PyLevelLootManager_classes.hpp"
#include "PyLevelLootManager_parameters.hpp"


SDK_NAMESPACE_START

// PythonFunction PyLevelLootManager.PyLevelLootManager.ReceiveInit
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void APyLevelLootManager::ReceiveInit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyLevelLootManager", "ReceiveInit");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyLevelLootManager.PyLevelLootManager.ReceiveBeginPlay
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void APyLevelLootManager::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyLevelLootManager", "ReceiveBeginPlay");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyLevelLootManager.PyLevelLootManager.ReceiveEndPlay
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APyLevelLootManager::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyLevelLootManager", "ReceiveEndPlay");

	Params::PyLevelLootManager_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyLevelLootManager.PyLevelLootManager.ReceiveTick
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APyLevelLootManager::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyLevelLootManager", "ReceiveTick");

	Params::PyLevelLootManager_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyLevelLootManager.PyLevelLootManager.K2_PreReplicatedRemove
// (Native, Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   LootID                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FRepMarvelLootMovement*          LootMovement                                           (Parm, OutParm, NoDestructor)

void APyLevelLootManager::K2_PreReplicatedRemove(int32 LootID, struct FRepMarvelLootMovement* LootMovement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyLevelLootManager", "K2_PreReplicatedRemove");

	Params::PyLevelLootManager_K2_PreReplicatedRemove Parms{};

	Parms.LootID = LootID;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (LootMovement != nullptr)
		*LootMovement = std::move(Parms.LootMovement);
}


// PythonFunction PyLevelLootManager.PyLevelLootManager.K2_PostReplicatedAdd
// (Native, Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   LootID                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FRepMarvelLootMovement*          LootMovement                                           (Parm, OutParm, NoDestructor)

void APyLevelLootManager::K2_PostReplicatedAdd(int32 LootID, struct FRepMarvelLootMovement* LootMovement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyLevelLootManager", "K2_PostReplicatedAdd");

	Params::PyLevelLootManager_K2_PostReplicatedAdd Parms{};

	Parms.LootID = LootID;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (LootMovement != nullptr)
		*LootMovement = std::move(Parms.LootMovement);
}


// PythonFunction PyLevelLootManager.PyLevelLootManager.K2_PostReplicatedChange
// (Native, Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   LootID                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FRepMarvelLootMovement*          LootMovement                                           (Parm, OutParm, NoDestructor)

void APyLevelLootManager::K2_PostReplicatedChange(int32 LootID, struct FRepMarvelLootMovement* LootMovement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyLevelLootManager", "K2_PostReplicatedChange");

	Params::PyLevelLootManager_K2_PostReplicatedChange Parms{};

	Parms.LootID = LootID;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (LootMovement != nullptr)
		*LootMovement = std::move(Parms.LootMovement);
}


SDK_NAMESPACE_END
