#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyM2201DuelLivePanel

#include "Basic.hpp"

#include "PyM2201DuelLivePanel_classes.hpp"
#include "PyM2201DuelLivePanel_parameters.hpp"


SDK_NAMESPACE_START

// PythonFunction PyM2201DuelLivePanel.PyM2201DuelLivePanel.ReceiveBeginPlay
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void APyM2201DuelLivePanel::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyM2201DuelLivePanel", "ReceiveBeginPlay");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyM2201DuelLivePanel.PyM2201DuelLivePanel.ReceiveEndPlay
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APyM2201DuelLivePanel::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyM2201DuelLivePanel", "ReceiveEndPlay");

	Params::PyM2201DuelLivePanel_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyM2201DuelLivePanel.PyM2201DuelLivePanel.SetViewTargetPlayerState
// (Native, Public, BlueprintCallable)
// Parameters:
// class AMarvelPlayerState*               ViewTargetPlayerState                                  (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void APyM2201DuelLivePanel::SetViewTargetPlayerState(class AMarvelPlayerState* ViewTargetPlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyM2201DuelLivePanel", "SetViewTargetPlayerState");

	Params::PyM2201DuelLivePanel_SetViewTargetPlayerState Parms{};

	Parms.ViewTargetPlayerState = ViewTargetPlayerState;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyM2201DuelLivePanel.PyM2201DuelLiveManager.Get
// (Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class UObject*                          WCO                                                    (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UObject*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

class UObject* UPyM2201DuelLiveManager::Get(class UObject* WCO)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("PyM2201DuelLiveManager", "Get");

	Params::PyM2201DuelLiveManager_Get Parms{};

	Parms.WCO = WCO;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// PythonFunction PyM2201DuelLivePanel.PyM2201DuelLiveCamera.ReceiveBeginPlay
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void APyM2201DuelLiveCamera::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyM2201DuelLiveCamera", "ReceiveBeginPlay");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyM2201DuelLivePanel.PyM2201DuelLiveCamera.ReceiveTick
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APyM2201DuelLiveCamera::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyM2201DuelLiveCamera", "ReceiveTick");

	Params::PyM2201DuelLiveCamera_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyM2201DuelLivePanel.PyM2201DuelLiveCamera.ReceiveEndPlay
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APyM2201DuelLiveCamera::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyM2201DuelLiveCamera", "ReceiveEndPlay");

	Params::PyM2201DuelLiveCamera_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyM2201DuelLivePanel.PyM2201DuelLiveCamera.UpdateCaptureMethod
// (Native, Public, BlueprintCallable)

void APyM2201DuelLiveCamera::UpdateCaptureMethod()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyM2201DuelLiveCamera", "UpdateCaptureMethod");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyM2201DuelLivePanel.PyM2201DuelLiveCamera.SetViewTargetPlayerState
// (Native, Public, BlueprintCallable)
// Parameters:
// class AMarvelPlayerState*               ViewTargetPlayerState                                  (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void APyM2201DuelLiveCamera::SetViewTargetPlayerState(class AMarvelPlayerState* ViewTargetPlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyM2201DuelLiveCamera", "SetViewTargetPlayerState");

	Params::PyM2201DuelLiveCamera_SetViewTargetPlayerState Parms{};

	Parms.ViewTargetPlayerState = ViewTargetPlayerState;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


SDK_NAMESPACE_END
