#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyNewYorkH01CathedralBell

#include "Basic.hpp"

#include "Engine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// PythonFunction PyNewYorkH01CathedralBell.PyNewYorkH01CathedralBellSounds.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct PyNewYorkH01CathedralBellSounds_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndPlayReason;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyNewYorkH01CathedralBellSounds_ReceiveEndPlay;

// PythonFunction PyNewYorkH01CathedralBell.PyNewYorkH01CathedralBellSounds.PostBellSoundEvent
// 0x0004 (0x0004 - 0x0000)
struct PyNewYorkH01CathedralBellSounds_PostBellSoundEvent final
{
public:
	int32                                         phase;                                             // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyNewYorkH01CathedralBellSounds_PostBellSoundEvent;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
