#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyPlayerState2201Component

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"
#include "MarvelLevel_structs.hpp"
#include "Engine_structs.hpp"
#include "python_enums_structs.hpp"


SDK_NAMESPACE_START

// PythonClass PyPlayerState2201Component.PyPlayerState2201Component
// 0x0178 (0x0280 - 0x0108)
class UPyPlayerState2201Component final : public UMarvelActorComponentBase
{
public:
	bool                                          bClassicDuelSettingInited;                         // 0x0108(0x0001)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bRandomDuelSettingInited;                          // 0x0109(0x0001)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSpecialDuelSettingInited;                         // 0x010A(0x0001)(Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_10B[0x5];                                      // 0x010B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 DuelQueueCancelReason;                             // 0x0110(0x0010)(Net, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EDuelProcessState                             M2201DuelProcessState;                             // 0x0120(0x0001)(Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_121[0x7];                                      // 0x0121(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FReplicateTimer                        WaitingTimer;                                      // 0x0128(0x0078)(BlueprintVisible, Net, NativeAccessSpecifierPublic)
	bool                                          Initiator;                                         // 0x01A0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          InCarriageCooldown;                                // 0x01A1(0x0001)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1A2[0x6];                                      // 0x01A2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FReplicateTimer                        CarriageCooldownTimer;                             // 0x01A8(0x0078)(Net, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(bool Initiator_0)> OnInitiatorChanged;                             // 0x0220(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(EDuelType DuelType)> NotifyDuelTypeChanged;                        // 0x0230(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnDuelQueueIndexChanged;                           // 0x0240(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(EDuelProcessState State)> OnM2201DuelProcessStateChanged;          // 0x0250(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnDuelIncoming;                                    // 0x0260(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(bool IsInitiator, int32 EnemyUID)> OnEnterTips;                    // 0x0270(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	void ReceiveBeginPlay();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void OnRep_M2201DuelProcessState();
	void OnRep_Initiator();
	void SyncDuelSetting(EDuelType duel_type, const class FString& duel_setting);
	void StartDuel(EDuelType duel_type);
	void StartDuelWithSetting(EDuelType duel_type, const class FString& duel_setting);
	void S_waiting_end_callback();
	void ClientNotifyDuelTypeChanged(EDuelType DuelType);
	void Server_InviteToDuel(int32 self_player_uid, int32 target_player_uid, const class FString& invitation_msg, bool is_public, EDuelType duel_type, const class FString& duel_setting);
	void Server_ProcessDuelInvitation(int32 initiator_uid, int32 receiver_uid, bool is_public);
	void Server_CancelDuel(int32 duel_queue_index);
	void Client_UpdateInvitedUidTimestampDict(int32 invited_uid, float timestamp);
	void Client_ClearInvitedUidTimestampDict();
	void Client_OnInvitedToDuel(int32 initiator_uid, int32 receiver_uid, const class FString& invitation_msg, bool is_public, EDuelType duel_type, const class FString& duel_setting);
	void Client_NotifyDuelMsg(const class FString& key_str);
	void Client_NotifyDuelInvitationSucceed(const class FString& key_str, const class FString& player_name);
	void Client_PlayLevelPortalFX(const struct FVector& FromLocation, const struct FVector& ToLocation);
	void Client_NotifyPrivateDuelCancel();
	void Client_NotifyForceGetOutCarriage();
	void Client_NotifyDuelIncoming();
	void ServerMarkPlayTransferDisappear();
	void ClientNotifyPlayTransferDisappear(const struct FVector& SourceLocation, const struct FRotator& SourceRotation);
	void TriggerPlayTransferAppear();
	void ClientNotifyPlayTransferAppear(const struct FVector& TargetLocation, const struct FRotator& TargetRotation);
	void MulticastNotifyPlayTransferAudio();
	void ClientNotifyEnterTips(bool IsInitiator, int32 EnemyUID);
	void Client_NotifyDuelLoading(float show_time);
	void Client_NotifyReturnToM2201();
	void OnA172CoolDownFinished();
	void OnRep_InCarriageCooldown();
	void Server_RequestLotteryMachineShuffle(const class FString& actor_name);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyPlayerState2201Component")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyPlayerState2201Component")
	}
	static class UPyPlayerState2201Component* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyPlayerState2201Component>();
	}
};
DUMPER7_ASSERTS_UPyPlayerState2201Component;

SDK_NAMESPACE_END
