#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyUI_101654

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// PythonFunction PyUI_101654.PyWidget_AbilityHUD_101654.OnVisibleChanged
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_AbilityHUD_101654_OnVisibleChanged final
{
public:
	bool                                          bNewVisible;                                       // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyWidget_AbilityHUD_101654_OnVisibleChanged;

// PythonFunction PyUI_101654.PyWidget_AbilityHUD_101654.OnAnimationFinished
// 0x0008 (0x0008 - 0x0000)
struct PyWidget_AbilityHUD_101654_OnAnimationFinished final
{
public:
	const class UWidgetAnimation*                 Animation;                                         // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyWidget_AbilityHUD_101654_OnAnimationFinished;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
