#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Activity205_Schedule_MissionTab

#include "Basic.hpp"

#include "PyWidget_Activity205_Schedule_MissionTab_classes.hpp"
#include "PyWidget_Activity205_Schedule_MissionTab_parameters.hpp"


SDK_NAMESPACE_START

// PythonFunction PyWidget_Activity205_Schedule_MissionTab.PyWidget_Activity205_Schedule_MissionTab.OnInitialized
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget_Activity205_Schedule_MissionTab::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_Activity205_Schedule_MissionTab", "OnInitialized");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_Activity205_Schedule_MissionTab.PyWidget_Activity205_Schedule_MissionTab.Destruct
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget_Activity205_Schedule_MissionTab::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_Activity205_Schedule_MissionTab", "Destruct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


SDK_NAMESPACE_END
