#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Lottery3D_Rule

#include "Basic.hpp"

#include "PyWidget_Common_SeasonStory_Rule_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyWidget_Lottery3D_Rule.PyWidget_Lottery3D_Rule
// 0x0008 (0x0648 - 0x0640)
class UPyWidget_Lottery3D_Rule final : public UPyWidget_Common_SeasonStory_Rule
{
public:
	TSubclassOf<class UUserWidget>                ProbabilityItem;                                   // 0x0640(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void OnCascadingVisibleChanged(bool bNewVisible);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_Lottery3D_Rule")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_Lottery3D_Rule")
	}
	static class UPyWidget_Lottery3D_Rule* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Lottery3D_Rule>();
	}
};
DUMPER7_ASSERTS_UPyWidget_Lottery3D_Rule;

SDK_NAMESPACE_END
