#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_LeagueSubscribe_Calendar_SideExpansion_SubscribeMatch

#include "Basic.hpp"

#include "PyWidget_LeagueSubscribe_Calendar_SideExpansion_SubscribeMatch_classes.hpp"
#include "PyWidget_LeagueSubscribe_Calendar_SideExpansion_SubscribeMatch_parameters.hpp"


SDK_NAMESPACE_START

// PythonFunction PyWidget_LeagueSubscribe_Calendar_SideExpansion_SubscribeMatch.PyWidget_LeagueSubscribe_Calendar_SideExpansion_SubscribeMatch.Construct
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget_LeagueSubscribe_Calendar_SideExpansion_SubscribeMatch::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_LeagueSubscribe_Calendar_SideExpansion_SubscribeMatch", "Construct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_LeagueSubscribe_Calendar_SideExpansion_SubscribeMatch.PyWidget_LeagueSubscribe_Calendar_SideExpansion_SubscribeMatch.OnCascadingVisibleChanged
// (Native, Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bNewVisible                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPyWidget_LeagueSubscribe_Calendar_SideExpansion_SubscribeMatch::OnCascadingVisibleChanged(bool bNewVisible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_LeagueSubscribe_Calendar_SideExpansion_SubscribeMatch", "OnCascadingVisibleChanged");

	Params::PyWidget_LeagueSubscribe_Calendar_SideExpansion_SubscribeMatch_OnCascadingVisibleChanged Parms{};

	Parms.bNewVisible = bNewVisible;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyWidget_LeagueSubscribe_Calendar_SideExpansion_SubscribeMatch.PyWidget_LeagueSubscribe_Calendar_SideExpansion_SubscribeMatch.Destruct
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget_LeagueSubscribe_Calendar_SideExpansion_SubscribeMatch::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_LeagueSubscribe_Calendar_SideExpansion_SubscribeMatch", "Destruct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


SDK_NAMESPACE_END
