#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_HomeEntrance_Activity_Item_173

#include "Basic.hpp"

#include "PyWidget_ActivityExpBpBase_HomeEntrance_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyWidget_HomeEntrance_Activity_Item_173.PyWidget_HomeEntrance_Activity_Item_173
// 0x0000 (0x0640 - 0x0640)
class UPyWidget_HomeEntrance_Activity_Item_173 final : public UPyWidget_ActivityExpBpBase_HomeEntrance
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_HomeEntrance_Activity_Item_173")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_HomeEntrance_Activity_Item_173")
	}
	static class UPyWidget_HomeEntrance_Activity_Item_173* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_HomeEntrance_Activity_Item_173>();
	}
};
DUMPER7_ASSERTS_UPyWidget_HomeEntrance_Activity_Item_173;

SDK_NAMESPACE_END
