#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_HeroSystem_ListCard_V2

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// PythonFunction PyWidget_HeroSystem_ListCard_V2.PyWidget_HeroSystem_ListCard_V2.OnCascadingVisibleChanged
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_HeroSystem_ListCard_V2_OnCascadingVisibleChanged final
{
public:
	bool                                          bNewVisible;                                       // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyWidget_HeroSystem_ListCard_V2_OnCascadingVisibleChanged;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
