#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_LCMN_ClanPreview_MainPanel

#include "Basic.hpp"

#include "PyWidget_ModuleMainPanel_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyWidget_LCMN_ClanPreview_MainPanel.PyWidget_LCMN_ClanPreview_MainPanel
// 0x0000 (0x0630 - 0x0630)
class UPyWidget_LCMN_ClanPreview_MainPanel final : public UPyWidget_ModuleMainPanel
{
public:
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_LCMN_ClanPreview_MainPanel")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_LCMN_ClanPreview_MainPanel")
	}
	static class UPyWidget_LCMN_ClanPreview_MainPanel* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_LCMN_ClanPreview_MainPanel>();
	}
};
DUMPER7_ASSERTS_UPyWidget_LCMN_ClanPreview_MainPanel;

SDK_NAMESPACE_END
