#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_League_ScoreIcon

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "PyMarvelUserWidget_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyWidget_League_ScoreIcon.PyWidget_League_ScoreIcon
// 0x0010 (0x0608 - 0x05F8)
class UPyWidget_League_ScoreIcon final : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5F2[0x6];                                      // 0x05F2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              Size_MarvelOverlay;                                // 0x05F8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void PreConstruct(bool IsDesignTime);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_League_ScoreIcon")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_League_ScoreIcon")
	}
	static class UPyWidget_League_ScoreIcon* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_League_ScoreIcon>();
	}
};
DUMPER7_ASSERTS_UPyWidget_League_ScoreIcon;

SDK_NAMESPACE_END
