#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Activity181_MainPanel

#include "Basic.hpp"

#include "PyWidget_ModuleMainPanel_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyWidget_Activity181_MainPanel.PyWidget_Activity181_MainPanel
// 0x0000 (0x0630 - 0x0630)
class UPyWidget_Activity181_MainPanel final : public UPyWidget_ModuleMainPanel
{
public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void OnAnimationFinished(const class UWidgetAnimation* Animation);
	void TimeToPlayItemAnimation(int32 index);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_Activity181_MainPanel")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_Activity181_MainPanel")
	}
	static class UPyWidget_Activity181_MainPanel* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Activity181_MainPanel>();
	}
};
DUMPER7_ASSERTS_UPyWidget_Activity181_MainPanel;

SDK_NAMESPACE_END
