#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_AbilityIntroPanel

#include "Basic.hpp"

#include "PyWidget_Button_classes.hpp"
#include "PyWidget_AbilityIntroPanel_structs.hpp"
#include "Marvel_structs.hpp"
#include "python_enums_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "PyWidget_ModuleMainPanel_classes.hpp"
#include "PyMarvelUserWidget_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyWidget_AbilityIntroPanel.PyWidget_AbilityIntroShapeLabel
// 0x0008 (0x07B8 - 0x07B0)
class UPyWidget_AbilityIntroShapeLabel : public UPyWidget_Button
{
public:
	bool                                          IsSelected;                                        // 0x07B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsHovered_PyWidget_AbilityIntroShapeLabel;         // 0x07B1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void PreConstruct(bool IsDesignTime);
	void SetSelected(bool IsSelected_0);
	void SetIsHover(bool IsHover_0);
	void SetHeroID(int32 HeroID, int32 ShapeID, int32 PageID, EHeroRole HeroRole);
	void OnHeroIconNoSelectedLoad(class UTexture2D* Picture);
	void OnHeroIconSelectedLoad(class UTexture2D* Picture);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_AbilityIntroShapeLabel")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_AbilityIntroShapeLabel")
	}
	static class UPyWidget_AbilityIntroShapeLabel* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_AbilityIntroShapeLabel>();
	}
};
DUMPER7_ASSERTS_UPyWidget_AbilityIntroShapeLabel;

// PythonClass PyWidget_AbilityIntroPanel.PyAbilityIntroRichTableAsset
// 0x00B0 (0x00E8 - 0x0038)
class UPyAbilityIntroRichTableAsset final : public UPrimaryDataAsset
{
public:
	TMap<EAbilityIntroRichTableType, class UDataTable*> TextStyleSetDict;                            // 0x0038(0x0050)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	TArray<ELanguageType>                         ForceNormalStyleLanguageList;                      // 0x0088(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	TMap<int32, TArray<ELanguageType>>            ForceSmallStyleHeroLanguageDict;                   // 0x0098(0x0050)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyAbilityIntroRichTableAsset")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyAbilityIntroRichTableAsset")
	}
	static class UPyAbilityIntroRichTableAsset* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbilityIntroRichTableAsset>();
	}
};
DUMPER7_ASSERTS_UPyAbilityIntroRichTableAsset;

// PythonClass PyWidget_AbilityIntroPanel.PyWidget_PageListUnit
// 0x0058 (0x0650 - 0x05F8)
class UPyWidget_PageListUnit final : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5F2[0x6];                                      // 0x05F2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<ESkillListUnitStyle, struct FSkillListUnitStyleConfig> ColorStyles;                         // 0x05F8(0x0050)(Edit, DisableEditOnInstance, NativeAccessSpecifierPublic)
	ESkillListUnitStyle                           ColorType;                                         // 0x0648(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void PreConstruct(bool IsDesignTime);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_PageListUnit")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_PageListUnit")
	}
	static class UPyWidget_PageListUnit* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_PageListUnit>();
	}
};
DUMPER7_ASSERTS_UPyWidget_PageListUnit;

// PythonClass PyWidget_AbilityIntroPanel.PyWidget_AbilityIntroUnit
// 0x0040 (0x0638 - 0x05F8)
class UPyWidget_AbilityIntroUnit : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5F2[0x2];                                      // 0x05F2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         NormalFontSize;                                    // 0x05F4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SmallFontSize;                                     // 0x05F8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5FC[0x4];                                      // 0x05FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             TextureNormal;                                     // 0x0600(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             TexturePassive;                                    // 0x0608(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             TextureSpecial;                                    // 0x0610(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RichInlineImageScale;                              // 0x0618(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_61C[0x4];                                      // 0x061C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UUserWidget>                PageListUnitClass;                                 // 0x0620(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class UTexture2D*>                     AbilityLevelIconWithActivity10130;                 // 0x0628(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_AbilityIntroUnit")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_AbilityIntroUnit")
	}
	static class UPyWidget_AbilityIntroUnit* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_AbilityIntroUnit>();
	}
};
DUMPER7_ASSERTS_UPyWidget_AbilityIntroUnit;

// PythonClass PyWidget_AbilityIntroPanel.PyWidget_AbilityIntroWeaponUnit
// 0x0000 (0x0638 - 0x0638)
class UPyWidget_AbilityIntroWeaponUnit final : public UPyWidget_AbilityIntroUnit
{
public:
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_AbilityIntroWeaponUnit")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_AbilityIntroWeaponUnit")
	}
	static class UPyWidget_AbilityIntroWeaponUnit* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_AbilityIntroWeaponUnit>();
	}
};
DUMPER7_ASSERTS_UPyWidget_AbilityIntroWeaponUnit;

// PythonClass PyWidget_AbilityIntroPanel.PyWidget_AbilityIntroPanel
// 0x00A8 (0x06D8 - 0x0630)
class UPyWidget_AbilityIntroPanel final : public UPyWidget_ModuleMainPanel
{
public:
	class UTexture2D*                             StarEmpty;                                         // 0x0630(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             StarFull;                                          // 0x0638(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCurveFloat*                            CurvePadding;                                      // 0x0640(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCurveFloat*                            CurvePadding_Left;                                 // 0x0648(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              DefaultSlotPaddingLeft;                            // 0x0650(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              DefaultSlotPaddingRight;                           // 0x0660(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UInputAction*                           IA_NextSculpt;                                     // 0x0670(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UInputAction*                           IA_PrevSculpt;                                     // 0x0678(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class UUserWidget>                CollaborativeAbilityClass;                         // 0x0680(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class UUserWidget>                NormalAbilityClass;                                // 0x0688(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class UUserWidget>                PassiveAbilityClass;                               // 0x0690(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class UUserWidget>                UltimateAbilityClass;                              // 0x0698(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class UUserWidget>                WeaponAbilityClass;                                // 0x06A0(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class UUserWidget>                TitleAbilityIconClass;                             // 0x06A8(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          AkEvent_ChangePage;                                // 0x06B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UPyWidget_Common_HeroRoleIcon*          WBP_Common_HeroRoleIcon;                           // 0x06B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FText                                   ControlTagSuffix;                                  // 0x06C0(0x0018)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void OnInputTypeChanged(Marvel::EInputType OldType, Marvel::EInputType NewType);
	void OnBecomeTop();
	void OnBecomeNoneTop();
	void OnSoftTextureLoad(class UUserWidget* HeroPortrait, class UObject* Texture);
	void OnHeroPortraitLoaded(class UTexture2D* Picture);
	void OnHeroPortrai2tLoaded(class UTexture2D* Picture);
	void OnHeroLogoLoaded(class UTexture2D* Picture);
	void OnAnimationFinished(const class UWidgetAnimation* Animation);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_AbilityIntroPanel")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_AbilityIntroPanel")
	}
	static class UPyWidget_AbilityIntroPanel* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_AbilityIntroPanel>();
	}
};
DUMPER7_ASSERTS_UPyWidget_AbilityIntroPanel;

// PythonClass PyWidget_AbilityIntroPanel.PyWidget_AbilityIntroUltimateUnit
// 0x0000 (0x0638 - 0x0638)
class UPyWidget_AbilityIntroUltimateUnit final : public UPyWidget_AbilityIntroUnit
{
public:
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_AbilityIntroUltimateUnit")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_AbilityIntroUltimateUnit")
	}
	static class UPyWidget_AbilityIntroUltimateUnit* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_AbilityIntroUltimateUnit>();
	}
};
DUMPER7_ASSERTS_UPyWidget_AbilityIntroUltimateUnit;

// PythonClass PyWidget_AbilityIntroPanel.PyWidget_TitleAbilityIconUnit
// 0x0000 (0x05F8 - 0x05F8)
class UPyWidget_TitleAbilityIconUnit final : public UPyMarvelUserWidget
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_TitleAbilityIconUnit")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_TitleAbilityIconUnit")
	}
	static class UPyWidget_TitleAbilityIconUnit* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_TitleAbilityIconUnit>();
	}
};
DUMPER7_ASSERTS_UPyWidget_TitleAbilityIconUnit;

// PythonClass PyWidget_AbilityIntroPanel.PyAbilityIntroExtendBase
// 0x0000 (0x0030 - 0x0030)
class UPyAbilityIntroExtendBase : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyAbilityIntroExtendBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyAbilityIntroExtendBase")
	}
	static class UPyAbilityIntroExtendBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbilityIntroExtendBase>();
	}
};
DUMPER7_ASSERTS_UPyAbilityIntroExtendBase;

SDK_NAMESPACE_END
