#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_League_PreviewItem

#include "Basic.hpp"

#include "PyWidget_ModuleMainPanel_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyWidget_League_PreviewItem.PyWidget_League_PreviewItem
// 0x0000 (0x0630 - 0x0630)
class UPyWidget_League_PreviewItem final : public UPyWidget_ModuleMainPanel
{
public:
	void OnInitialized();
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_League_PreviewItem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_League_PreviewItem")
	}
	static class UPyWidget_League_PreviewItem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_League_PreviewItem>();
	}
};
DUMPER7_ASSERTS_UPyWidget_League_PreviewItem;

SDK_NAMESPACE_END
