#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_LocalBattleKillTest

#include "Basic.hpp"

#include "Marvel_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// PythonFunction PyWidget_LocalBattleKillTest.PyWidget_LocalBattleKillPanelUnit.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_LocalBattleKillPanelUnit_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyWidget_LocalBattleKillPanelUnit_PreConstruct;

// PythonFunction PyWidget_LocalBattleKillTest.PyWidget_LocalBattleKillPanelUnit.OnVisibleChanged
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_LocalBattleKillPanelUnit_OnVisibleChanged final
{
public:
	bool                                          bNewVisible;                                       // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyWidget_LocalBattleKillPanelUnit_OnVisibleChanged;

// PythonFunction PyWidget_LocalBattleKillTest.PyWidget_LocalBattleKillPanelUnit.OnAnimationFinished
// 0x0008 (0x0008 - 0x0000)
struct PyWidget_LocalBattleKillPanelUnit_OnAnimationFinished final
{
public:
	const class UWidgetAnimation*                 Animation;                                         // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyWidget_LocalBattleKillPanelUnit_OnAnimationFinished;

// PythonFunction PyWidget_LocalBattleKillTest.PyWidget_LocalBattleKillPanel.OnKillingSpreeCountChanged
// 0x0010 (0x0010 - 0x0000)
struct PyWidget_LocalBattleKillPanel_OnKillingSpreeCountChanged final
{
public:
	int32                                         Count;                                             // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AMarvelPlayerState*                     ps;                                                // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyWidget_LocalBattleKillPanel_OnKillingSpreeCountChanged;

// PythonFunction PyWidget_LocalBattleKillTest.PyWidget_LocalBattleKillPanel.OnPickUpKillConfirm
// 0x0018 (0x0018 - 0x0000)
struct PyWidget_LocalBattleKillPanel_OnPickUpKillConfirm final
{
public:
	class AActor*                                 Item;                                              // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AMarvelPlayerState*                     PlayerState;                                       // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EBattleSide                                   BattleSide;                                        // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsAlly;                                            // 0x0011(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyWidget_LocalBattleKillPanel_OnPickUpKillConfirm;

// PythonFunction PyWidget_LocalBattleKillTest.PyWidget_LocalBattleKillPanel.OnActorDeathDispatcher
// 0x0030 (0x0030 - 0x0000)
struct PyWidget_LocalBattleKillPanel_OnActorDeathDispatcher final
{
public:
	class AActor*                                 Source;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Target;                                            // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FAttributeModifierHandle               ModifierHandle;                                    // 0x0010(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
	struct FGlobalEventExtraData                  ExtraData;                                         // 0x0028(0x0001)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor)
};
DUMPER7_ASSERTS_PyWidget_LocalBattleKillPanel_OnActorDeathDispatcher;

// PythonFunction PyWidget_LocalBattleKillTest.PyWidget_LocalBattleKillPanelCenter.OnAnimationFinished
// 0x0008 (0x0008 - 0x0000)
struct PyWidget_LocalBattleKillPanelCenter_OnAnimationFinished final
{
public:
	const class UWidgetAnimation*                 Animation;                                         // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyWidget_LocalBattleKillPanelCenter_OnAnimationFinished;

// PythonFunction PyWidget_LocalBattleKillTest.PyWidget_LocalBattleKillReticleCenter.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_LocalBattleKillReticleCenter_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PyWidget_LocalBattleKillReticleCenter_PreConstruct;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
