#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_StoreLottery_Flyer

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyWidget_StoreLottery_Flyer.PyWidget_StoreLottery_Flyer
// 0x0010 (0x0608 - 0x05F8)
class UPyWidget_StoreLottery_Flyer final : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5F2[0x6];                                      // 0x05F2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UCurveFloat*                            TraceCurve;                                        // 0x05F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MoveTime;                                          // 0x0600(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         IntervalTime;                                      // 0x0604(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void Construct();
	void Destruct();
	void OnCascadingVisibleChanged(bool bNewVisible);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_StoreLottery_Flyer")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_StoreLottery_Flyer")
	}
	static class UPyWidget_StoreLottery_Flyer* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_StoreLottery_Flyer>();
	}
};
DUMPER7_ASSERTS_UPyWidget_StoreLottery_Flyer;

SDK_NAMESPACE_END
