#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Esports_PlayerOperate_InfoPanel

#include "Basic.hpp"

#include "PyWidget_SecondaryChildBase_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyWidget_Esports_PlayerOperate_InfoPanel.PyWidget_Esports_PlayerOperate_InfoPanel
// 0x0000 (0x05F8 - 0x05F8)
class UPyWidget_Esports_PlayerOperate_InfoPanel final : public UPyWidget_SecondaryChildBase
{
public:
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_Esports_PlayerOperate_InfoPanel")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_Esports_PlayerOperate_InfoPanel")
	}
	static class UPyWidget_Esports_PlayerOperate_InfoPanel* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Esports_PlayerOperate_InfoPanel>();
	}
};
DUMPER7_ASSERTS_UPyWidget_Esports_PlayerOperate_InfoPanel;

SDK_NAMESPACE_END
