#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_MatchSeries_ClanViewItem

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "PyMarvelListEntryWidget_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyWidget_MatchSeries_ClanViewItem.PyWidget_MatchSeries_ClanViewItem
// 0x0030 (0x0658 - 0x0628)
class UPyWidget_MatchSeries_ClanViewItem final : public UPyMarvelListEntryWidget
{
public:
	struct FLinearColor                           ClanHoverColor_Normal;                             // 0x0628(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           ClanHoverColor_ScoreHidden;                        // 0x0638(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           ClanHoverColor_InProgress;                         // 0x0648(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_MatchSeries_ClanViewItem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_MatchSeries_ClanViewItem")
	}
	static class UPyWidget_MatchSeries_ClanViewItem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_MatchSeries_ClanViewItem>();
	}
};
DUMPER7_ASSERTS_UPyWidget_MatchSeries_ClanViewItem;

SDK_NAMESPACE_END
