#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Activity169_Secondary_Exp

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "PyWidget_SecondaryChildBase_classes.hpp"


SDK_NAMESPACE_START

// PythonClass PyWidget_Activity169_Secondary_Exp.PyWidget_Activity169_Secondary_Exp
// 0x0030 (0x0628 - 0x05F8)
class UPyWidget_Activity169_Secondary_Exp final : public UPyWidget_SecondaryChildBase
{
public:
	uint8                                         Pad_5F2[0x2];                                      // 0x05F2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            ExpNumEnoughColor;                                 // 0x05F4(0x0014)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FSlateColor                            ExpNumInsufficientColor;                           // 0x0608(0x0014)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	uint8                                         Pad_61C[0x4];                                      // 0x061C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAkAudioEvent*                          SwitchHeroAudio;                                   // 0x0620(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void OnAnimationFinished(const class UWidgetAnimation* Animation);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyWidget_Activity169_Secondary_Exp")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyWidget_Activity169_Secondary_Exp")
	}
	static class UPyWidget_Activity169_Secondary_Exp* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Activity169_Secondary_Exp>();
	}
};
DUMPER7_ASSERTS_UPyWidget_Activity169_Secondary_Exp;

SDK_NAMESPACE_END
