#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_League_Ignite_Main_LeagueCardEntry

#include "Basic.hpp"

#include "PyWidget_League_Ignite_Main_LeagueCardEntry_classes.hpp"


SDK_NAMESPACE_START

// PythonFunction PyWidget_League_Ignite_Main_LeagueCardEntry.PyWidget_League_Ignite_Main_LeagueCardEntry.OnInitialized
// (BlueprintCosmetic, Native, Event, Protected, BlueprintCallable, BlueprintEvent)

void UPyWidget_League_Ignite_Main_LeagueCardEntry::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyWidget_League_Ignite_Main_LeagueCardEntry", "OnInitialized");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


SDK_NAMESPACE_END
