#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Scalability

#include "Basic.hpp"

#include "Marvel_classes.hpp"


SDK_NAMESPACE_START

// PythonClass Scalability.UISettingEntryViewDistanceQuality
// 0x0000 (0x0030 - 0x0030)
class UUISettingEntryViewDistanceQuality final : public UUISettingEntrySettingHandler
{
public:
	void BP_OnApply(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& p, const TMap<int32, class FText>& options, float value);
	float BP_GetCurrentValue(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& p, const TMap<int32, class FText>& o);
	TMap<class FString, int32> BP_OnChanged(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& params, const TMap<int32, class FText>& options, float value, const TMap<class FString, int32>& tags);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("UISettingEntryViewDistanceQuality")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UISettingEntryViewDistanceQuality")
	}
	static class UUISettingEntryViewDistanceQuality* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUISettingEntryViewDistanceQuality>();
	}
};
DUMPER7_ASSERTS_UUISettingEntryViewDistanceQuality;

// PythonClass Scalability.UISettingEntryScalabilityGenerator
// 0x0000 (0x0030 - 0x0030)
class UUISettingEntryScalabilityGenerator final : public UUISettingEntryOptionsGenerator
{
public:
	TMap<int32, class FText> BP_Gen(class UObject* obj, const class FString& setting_key, const TMap<int32, class FText>& options);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("UISettingEntryScalabilityGenerator")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UISettingEntryScalabilityGenerator")
	}
	static class UUISettingEntryScalabilityGenerator* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUISettingEntryScalabilityGenerator>();
	}
};
DUMPER7_ASSERTS_UUISettingEntryScalabilityGenerator;

// PythonClass Scalability.UISettingEntryScalabilityHandler
// 0x0000 (0x0030 - 0x0030)
class UUISettingEntryScalabilityHandler final : public UUISettingEntrySettingHandler
{
public:
	void BP_OnApply(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& p, const TMap<int32, class FText>& options, float value);
	float BP_GetCurrentValue(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& p, const TMap<int32, class FText>& o);
	TMap<class FString, int32> BP_OnChanged(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& params, const TMap<int32, class FText>& options, float value, const TMap<class FString, int32>& tags);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("UISettingEntryScalabilityHandler")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UISettingEntryScalabilityHandler")
	}
	static class UUISettingEntryScalabilityHandler* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUISettingEntryScalabilityHandler>();
	}
};
DUMPER7_ASSERTS_UUISettingEntryScalabilityHandler;

// PythonClass Scalability.UISettingEntryShadowQuality
// 0x0000 (0x0030 - 0x0030)
class UUISettingEntryShadowQuality final : public UUISettingEntrySettingHandler
{
public:
	void BP_OnApply(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& p, const TMap<int32, class FText>& options, float value);
	float BP_GetCurrentValue(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& p, const TMap<int32, class FText>& o);
	TMap<class FString, int32> BP_OnChanged(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& params, const TMap<int32, class FText>& options, float value, const TMap<class FString, int32>& tags);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("UISettingEntryShadowQuality")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UISettingEntryShadowQuality")
	}
	static class UUISettingEntryShadowQuality* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUISettingEntryShadowQuality>();
	}
};
DUMPER7_ASSERTS_UUISettingEntryShadowQuality;

// PythonClass Scalability.UISettingEntryGlobalIlluminationQuality
// 0x0000 (0x0030 - 0x0030)
class UUISettingEntryGlobalIlluminationQuality final : public UUISettingEntrySettingHandler
{
public:
	void BP_OnApply(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& p, const TMap<int32, class FText>& options, float value);
	float BP_GetCurrentValue(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& p, const TMap<int32, class FText>& o);
	TMap<class FString, int32> BP_OnChanged(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& params, const TMap<int32, class FText>& options, float value, const TMap<class FString, int32>& tags);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("UISettingEntryGlobalIlluminationQuality")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UISettingEntryGlobalIlluminationQuality")
	}
	static class UUISettingEntryGlobalIlluminationQuality* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUISettingEntryGlobalIlluminationQuality>();
	}
};
DUMPER7_ASSERTS_UUISettingEntryGlobalIlluminationQuality;

// PythonClass Scalability.UISettingEntryReflectionQuality
// 0x0000 (0x0030 - 0x0030)
class UUISettingEntryReflectionQuality final : public UUISettingEntrySettingHandler
{
public:
	void BP_OnApply(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& p, const TMap<int32, class FText>& options, float value);
	float BP_GetCurrentValue(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& p, const TMap<int32, class FText>& o);
	TMap<class FString, int32> BP_OnChanged(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& params, const TMap<int32, class FText>& options, float value, const TMap<class FString, int32>& tags);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("UISettingEntryReflectionQuality")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UISettingEntryReflectionQuality")
	}
	static class UUISettingEntryReflectionQuality* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUISettingEntryReflectionQuality>();
	}
};
DUMPER7_ASSERTS_UUISettingEntryReflectionQuality;

// PythonClass Scalability.UISettingEntryTextureQuality
// 0x0000 (0x0030 - 0x0030)
class UUISettingEntryTextureQuality final : public UUISettingEntrySettingHandler
{
public:
	void BP_OnApply(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& p, const TMap<int32, class FText>& options, float value);
	float BP_GetCurrentValue(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& p, const TMap<int32, class FText>& o);
	TMap<class FString, int32> BP_OnChanged(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& params, const TMap<int32, class FText>& options, float value, const TMap<class FString, int32>& tags);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("UISettingEntryTextureQuality")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UISettingEntryTextureQuality")
	}
	static class UUISettingEntryTextureQuality* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUISettingEntryTextureQuality>();
	}
};
DUMPER7_ASSERTS_UUISettingEntryTextureQuality;

// PythonClass Scalability.UISettingEntryVisualEffectQuality
// 0x0000 (0x0030 - 0x0030)
class UUISettingEntryVisualEffectQuality final : public UUISettingEntrySettingHandler
{
public:
	void BP_OnApply(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& p, const TMap<int32, class FText>& options, float value);
	float BP_GetCurrentValue(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& p, const TMap<int32, class FText>& o);
	TMap<class FString, int32> BP_OnChanged(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& params, const TMap<int32, class FText>& options, float value, const TMap<class FString, int32>& tags);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("UISettingEntryVisualEffectQuality")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UISettingEntryVisualEffectQuality")
	}
	static class UUISettingEntryVisualEffectQuality* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUISettingEntryVisualEffectQuality>();
	}
};
DUMPER7_ASSERTS_UUISettingEntryVisualEffectQuality;

// PythonClass Scalability.UISettingEntryPostProcessingQuality
// 0x0000 (0x0030 - 0x0030)
class UUISettingEntryPostProcessingQuality final : public UUISettingEntrySettingHandler
{
public:
	void BP_OnApply(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& p, const TMap<int32, class FText>& options, float value);
	float BP_GetCurrentValue(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& p, const TMap<int32, class FText>& o);
	TMap<class FString, int32> BP_OnChanged(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& params, const TMap<int32, class FText>& options, float value, const TMap<class FString, int32>& tags);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("UISettingEntryPostProcessingQuality")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UISettingEntryPostProcessingQuality")
	}
	static class UUISettingEntryPostProcessingQuality* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUISettingEntryPostProcessingQuality>();
	}
};
DUMPER7_ASSERTS_UUISettingEntryPostProcessingQuality;

// PythonClass Scalability.UISettingEntryFoliageQuality
// 0x0000 (0x0030 - 0x0030)
class UUISettingEntryFoliageQuality final : public UUISettingEntrySettingHandler
{
public:
	void BP_OnApply(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& p, const TMap<int32, class FText>& options, float value);
	float BP_GetCurrentValue(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& p, const TMap<int32, class FText>& o);
	TMap<class FString, int32> BP_OnChanged(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& params, const TMap<int32, class FText>& options, float value, const TMap<class FString, int32>& tags);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("UISettingEntryFoliageQuality")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UISettingEntryFoliageQuality")
	}
	static class UUISettingEntryFoliageQuality* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUISettingEntryFoliageQuality>();
	}
};
DUMPER7_ASSERTS_UUISettingEntryFoliageQuality;

// PythonClass Scalability.UISettingEntryShadingQuality
// 0x0000 (0x0030 - 0x0030)
class UUISettingEntryShadingQuality final : public UUISettingEntrySettingHandler
{
public:
	void BP_OnApply(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& p, const TMap<int32, class FText>& options, float value);
	float BP_GetCurrentValue(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& p, const TMap<int32, class FText>& o);
	TMap<class FString, int32> BP_OnChanged(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& params, const TMap<int32, class FText>& options, float value, const TMap<class FString, int32>& tags);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("UISettingEntryShadingQuality")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UISettingEntryShadingQuality")
	}
	static class UUISettingEntryShadingQuality* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUISettingEntryShadingQuality>();
	}
};
DUMPER7_ASSERTS_UUISettingEntryShadingQuality;

// PythonClass Scalability.UISettingEntryAntiAliasingQualityHandler
// 0x0000 (0x0030 - 0x0030)
class UUISettingEntryAntiAliasingQualityHandler final : public UUISettingEntrySettingHandler
{
public:
	void BP_OnApply(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& p, const TMap<int32, class FText>& options, float value);
	float BP_GetCurrentValue(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& p, const TMap<int32, class FText>& o);
	TMap<class FString, int32> BP_OnChanged(class UObject* obj, const class FString& setting_key, const TMap<class FString, class FString>& params, const TMap<int32, class FText>& options, float value, const TMap<class FString, int32>& tags);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("UISettingEntryAntiAliasingQualityHandler")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UISettingEntryAntiAliasingQualityHandler")
	}
	static class UUISettingEntryAntiAliasingQualityHandler* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUISettingEntryAntiAliasingQualityHandler>();
	}
};
DUMPER7_ASSERTS_UUISettingEntryAntiAliasingQualityHandler;

SDK_NAMESPACE_END
