#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TraceComponent_10396101_BP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass TraceComponent_10396101_BP.TraceComponent_10396101_BP_C
// 0x0000 (0x29F0 - 0x29F0)
class UTraceComponent_10396101_BP_C final : public UTraceComponent_Spread
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TraceComponent_10396101_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TraceComponent_10396101_BP_C")
	}
	static class UTraceComponent_10396101_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTraceComponent_10396101_BP_C>();
	}
};
DUMPER7_ASSERTS_UTraceComponent_10396101_BP_C;

SDK_NAMESPACE_END
