#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIController_SettingPage_Accessibility

#include "Basic.hpp"

#include "PyUIController_SettingPage_Base_classes.hpp"


SDK_NAMESPACE_START

// PythonClass UIController_SettingPage_Accessibility.PyUIController_SettingPage_Accessibility
// 0x0030 (0x0060 - 0x0030)
class UPyUIController_SettingPage_Accessibility : public UPyUIController_SettingPage_Base
{
public:
	class FText                                   Text_ColorVisionDeficiencyDesc;                    // 0x0030(0x0018)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	class FText                                   Text_FullScreenPreviewActionTip;                   // 0x0048(0x0018)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PyUIController_SettingPage_Accessibility")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PyUIController_SettingPage_Accessibility")
	}
	static class UPyUIController_SettingPage_Accessibility* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyUIController_SettingPage_Accessibility>();
	}
};
DUMPER7_ASSERTS_UPyUIController_SettingPage_Accessibility;

SDK_NAMESPACE_END
