#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Video_MRC

#include "Basic.hpp"

#include "PyWidget_VideoMRCEntry_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_Video_MRC.WBP_Video_MRC_C
// 0x0018 (0x0670 - 0x0658)
class UWBP_Video_MRC_C final : public UPyWidget_VideoMRCEntry
{
public:
	class UWidgetAnimation*                       Anime_FadeIn;                                      // 0x0658(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UMarvelImage*                           LeagueVideo;                                       // 0x0660(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               LeagueVideoSizeBox;                                // 0x0668(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Video_MRC_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Video_MRC_C")
	}
	static class UWBP_Video_MRC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Video_MRC_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Video_MRC_C;

SDK_NAMESPACE_END
