#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Multiplayer_Nameplate_SerialNumber

#include "Basic.hpp"

#include "PyWidget_Multiplayer_Nameplate_SerialNumber_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_Multiplayer_Nameplate_SerialNumber.WBP_Multiplayer_Nameplate_SerialNumber_C
// 0x0000 (0x0618 - 0x0618)
class UWBP_Multiplayer_Nameplate_SerialNumber_C final : public UPyWidget_Multiplayer_Nameplate_SerialNumber
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Multiplayer_Nameplate_SerialNumber_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Multiplayer_Nameplate_SerialNumber_C")
	}
	static class UWBP_Multiplayer_Nameplate_SerialNumber_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Multiplayer_Nameplate_SerialNumber_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Multiplayer_Nameplate_SerialNumber_C;

SDK_NAMESPACE_END
